# SPDX-License-Identifier: Apache-2.0

foreach(FSIM_REQUIRED IN ITEMS
    FSIM_SOURCE_DIR
    FSIM_BINARY_DIR
    FSIM_CMAKE_GENERATOR
    FSIM_CXX_COMPILER
    FSIM_BINDIR
    FSIM_LIBDIR
    FSIM_INCLUDEDIR
    FSIM_SCV_LIBRARY_NAME
    FSIM_SCV_RUNTIME_DIR
    FSIM_SYSTEMC_LIBRARY_NAME
    FSIM_SYSTEMC_RUNTIME_DIR)
  if(NOT DEFINED ${FSIM_REQUIRED} OR "${${FSIM_REQUIRED}}" STREQUAL "")
    message(FATAL_ERROR "${FSIM_REQUIRED} is required")
  endif()
endforeach()

set(FSIM_WORK_DIR "${FSIM_BINARY_DIR}/tests/scv-installed-consumer")
set(FSIM_INITIAL_STAGE "${FSIM_WORK_DIR}/initial-install")
set(FSIM_RELOCATED_STAGE "${FSIM_WORK_DIR}/relocated-install-é")
set(FSIM_CONSUMER_SOURCE "${FSIM_WORK_DIR}/consumer-source")
set(FSIM_CONSUMER_BUILD "${FSIM_WORK_DIR}/consumer-build")
file(REMOVE_RECURSE "${FSIM_WORK_DIR}")
file(MAKE_DIRECTORY "${FSIM_WORK_DIR}")

set(FSIM_INSTALL_COMMAND
  "${CMAKE_COMMAND}"
  --install "${FSIM_BINARY_DIR}"
  --prefix "${FSIM_INITIAL_STAGE}")
if(DEFINED FSIM_CONFIG AND NOT FSIM_CONFIG STREQUAL "")
  list(APPEND FSIM_INSTALL_COMMAND --config "${FSIM_CONFIG}")
endif()
execute_process(
  COMMAND ${FSIM_INSTALL_COMMAND}
  RESULT_VARIABLE FSIM_INSTALL_RESULT
  OUTPUT_VARIABLE FSIM_INSTALL_OUTPUT
  ERROR_VARIABLE FSIM_INSTALL_ERROR)
if(NOT FSIM_INSTALL_RESULT EQUAL 0)
  message(FATAL_ERROR
    "SCV staged install failed with ${FSIM_INSTALL_RESULT}\n"
    "${FSIM_INSTALL_OUTPUT}${FSIM_INSTALL_ERROR}")
endif()
file(RENAME "${FSIM_INITIAL_STAGE}" "${FSIM_RELOCATED_STAGE}")

set(FSIM_SCV_CONFIG_DIR
  "${FSIM_RELOCATED_STAGE}/${FSIM_LIBDIR}/cmake/SCV")
set(FSIM_SCV_LIBRARY
  "${FSIM_RELOCATED_STAGE}/${FSIM_SCV_RUNTIME_DIR}/${FSIM_SCV_LIBRARY_NAME}")
set(FSIM_SYSTEMC_LIBRARY
  "${FSIM_RELOCATED_STAGE}/${FSIM_SYSTEMC_RUNTIME_DIR}/${FSIM_SYSTEMC_LIBRARY_NAME}")
set(FSIM_EXPECTED_PATHS
  "${FSIM_RELOCATED_STAGE}/${FSIM_INCLUDEDIR}/scv.h"
  "${FSIM_RELOCATED_STAGE}/${FSIM_INCLUDEDIR}/scv/scv_bag.h"
  "${FSIM_RELOCATED_STAGE}/${FSIM_INCLUDEDIR}/fsim/systemc/scv.hpp"
  "${FSIM_SCV_CONFIG_DIR}/SCVConfig.cmake"
  "${FSIM_SCV_CONFIG_DIR}/SCVConfigVersion.cmake"
  "${FSIM_SCV_CONFIG_DIR}/SCVTargets.cmake"
  "${FSIM_RELOCATED_STAGE}/${FSIM_LIBDIR}/pkgconfig/scv.pc"
  "${FSIM_SCV_LIBRARY}"
  "${FSIM_SYSTEMC_LIBRARY}")
foreach(FSIM_PATH IN LISTS FSIM_EXPECTED_PATHS)
  if(NOT EXISTS "${FSIM_PATH}")
    message(FATAL_ERROR "installed SCV artifact is missing: ${FSIM_PATH}")
  endif()
endforeach()

file(GLOB FSIM_SCV_METADATA "${FSIM_SCV_CONFIG_DIR}/*.cmake")
list(APPEND FSIM_SCV_METADATA
  "${FSIM_RELOCATED_STAGE}/${FSIM_LIBDIR}/pkgconfig/scv.pc")
foreach(FSIM_METADATA IN LISTS FSIM_SCV_METADATA)
  file(READ "${FSIM_METADATA}" FSIM_METADATA_CONTENTS)
  foreach(FSIM_LEAK IN ITEMS
      "${FSIM_SOURCE_DIR}" "${FSIM_BINARY_DIR}" "${FSIM_INITIAL_STAGE}")
    string(FIND "${FSIM_METADATA_CONTENTS}" "${FSIM_LEAK}" FSIM_LEAK_INDEX)
    if(NOT FSIM_LEAK_INDEX EQUAL -1)
      message(FATAL_ERROR
        "installed SCV metadata leaks ${FSIM_LEAK}: ${FSIM_METADATA}")
    endif()
  endforeach()
endforeach()
file(READ
  "${FSIM_RELOCATED_STAGE}/${FSIM_LIBDIR}/pkgconfig/scv.pc"
  FSIM_SCV_PC)
foreach(FSIM_TOKEN IN ITEMS
    "prefix=\${pcfiledir}/../.."
    "Name: SCV"
    "Version: 2.0.1"
    "Requires: systemc = 3.0.2"
    "Libs: -L\${libdir} -lscv"
    "compatibility_schema=fsim-scv-compatibility-v1"
    "patch_sha256=61f2a7a414b317bba1f566bfd855c0ae1329c6f848d8bf5fa22b584c2f71969a"
    "artifact_schema=1"
    "cache_schema=1")
  string(FIND "${FSIM_SCV_PC}" "${FSIM_TOKEN}" FSIM_TOKEN_INDEX)
  if(FSIM_TOKEN_INDEX EQUAL -1)
    message(FATAL_ERROR "installed scv.pc omits ${FSIM_TOKEN}")
  endif()
endforeach()

file(MAKE_DIRECTORY "${FSIM_CONSUMER_SOURCE}")
file(WRITE "${FSIM_CONSUMER_SOURCE}/CMakeLists.txt" [=[
# SPDX-License-Identifier: Apache-2.0
cmake_minimum_required(VERSION 3.25)
project(fsim_scv_installed_consumer LANGUAGES CXX)
find_package(SCV 2.0.1 EXACT CONFIG REQUIRED)
add_executable(fsim_scv_installed_consumer main.cpp)
target_compile_features(fsim_scv_installed_consumer PRIVATE cxx_std_20)
target_link_libraries(fsim_scv_installed_consumer PRIVATE SCV::scv)
file(GENERATE OUTPUT "${CMAKE_BINARY_DIR}/consumer-path.txt"
  CONTENT "$<TARGET_FILE:fsim_scv_installed_consumer>")
]=])
file(WRITE "${FSIM_CONSUMER_SOURCE}/main.cpp" [=[
// SPDX-License-Identifier: Apache-2.0
#include <scv.h>
#include <fsim/systemc/scv.hpp>

int sc_main(int, char*[])
{
    static_assert(SCV_VERSION_MAJOR == 2);
    static_assert(SCV_VERSION_MINOR == 0);
    static_assert(SCV_VERSION_PATCH == 0);
    scv_bag<int> values { "installed-values", 173 };
    values.add(42);
    const auto& const_values = values;
    sc_core::sc_start(sc_core::SC_ZERO_TIME);
    return const_values.peekRandom() == 42
            && fsim_scv_accepts_compatibility_identity(
                fsim_scv_compatibility_identity())
        ? 0
        : 1;
}
]=])

set(FSIM_CONFIGURE_COMMAND
  "${CMAKE_COMMAND}"
  -S "${FSIM_CONSUMER_SOURCE}"
  -B "${FSIM_CONSUMER_BUILD}"
  -G "${FSIM_CMAKE_GENERATOR}"
  "-DCMAKE_PREFIX_PATH=${FSIM_RELOCATED_STAGE}"
  "-DCMAKE_CXX_COMPILER=${FSIM_CXX_COMPILER}")
if(DEFINED FSIM_CXX_FLAGS AND NOT FSIM_CXX_FLAGS STREQUAL "")
  list(APPEND FSIM_CONFIGURE_COMMAND "-DCMAKE_CXX_FLAGS=${FSIM_CXX_FLAGS}")
endif()
if(DEFINED FSIM_EXE_LINKER_FLAGS AND NOT FSIM_EXE_LINKER_FLAGS STREQUAL "")
  list(APPEND FSIM_CONFIGURE_COMMAND
    "-DCMAKE_EXE_LINKER_FLAGS=${FSIM_EXE_LINKER_FLAGS}")
endif()
if(DEFINED FSIM_MSVC_RUNTIME_LIBRARY
    AND NOT FSIM_MSVC_RUNTIME_LIBRARY STREQUAL "")
  list(APPEND FSIM_CONFIGURE_COMMAND
    "-DCMAKE_MSVC_RUNTIME_LIBRARY=${FSIM_MSVC_RUNTIME_LIBRARY}")
endif()
if(DEFINED FSIM_CMAKE_GENERATOR_PLATFORM
    AND NOT FSIM_CMAKE_GENERATOR_PLATFORM STREQUAL "")
  list(APPEND FSIM_CONFIGURE_COMMAND -A "${FSIM_CMAKE_GENERATOR_PLATFORM}")
endif()
if(DEFINED FSIM_CMAKE_GENERATOR_TOOLSET
    AND NOT FSIM_CMAKE_GENERATOR_TOOLSET STREQUAL "")
  list(APPEND FSIM_CONFIGURE_COMMAND -T "${FSIM_CMAKE_GENERATOR_TOOLSET}")
endif()
if(DEFINED FSIM_CMAKE_MAKE_PROGRAM
    AND NOT FSIM_CMAKE_MAKE_PROGRAM STREQUAL "")
  list(APPEND FSIM_CONFIGURE_COMMAND
    "-DCMAKE_MAKE_PROGRAM=${FSIM_CMAKE_MAKE_PROGRAM}")
endif()
if(DEFINED FSIM_CONFIG AND NOT FSIM_CONFIG STREQUAL "")
  list(APPEND FSIM_CONFIGURE_COMMAND "-DCMAKE_BUILD_TYPE=${FSIM_CONFIG}")
endif()
execute_process(
  COMMAND ${FSIM_CONFIGURE_COMMAND}
  RESULT_VARIABLE FSIM_CONFIGURE_RESULT
  OUTPUT_VARIABLE FSIM_CONFIGURE_OUTPUT
  ERROR_VARIABLE FSIM_CONFIGURE_ERROR)
if(NOT FSIM_CONFIGURE_RESULT EQUAL 0)
  message(FATAL_ERROR
    "installed SCV consumer configure failed with ${FSIM_CONFIGURE_RESULT}\n"
    "${FSIM_CONFIGURE_OUTPUT}${FSIM_CONFIGURE_ERROR}")
endif()

set(FSIM_BUILD_COMMAND
  "${CMAKE_COMMAND}" --build "${FSIM_CONSUMER_BUILD}" --parallel 8)
if(DEFINED FSIM_CONFIG AND NOT FSIM_CONFIG STREQUAL "")
  list(APPEND FSIM_BUILD_COMMAND --config "${FSIM_CONFIG}")
endif()
execute_process(
  COMMAND ${FSIM_BUILD_COMMAND}
  RESULT_VARIABLE FSIM_BUILD_RESULT
  OUTPUT_VARIABLE FSIM_BUILD_OUTPUT
  ERROR_VARIABLE FSIM_BUILD_ERROR)
if(NOT FSIM_BUILD_RESULT EQUAL 0)
  message(FATAL_ERROR
    "installed SCV consumer build failed with ${FSIM_BUILD_RESULT}\n"
    "${FSIM_BUILD_OUTPUT}${FSIM_BUILD_ERROR}")
endif()

set(FSIM_CONSUMER_PATH_FILE "${FSIM_CONSUMER_BUILD}/consumer-path.txt")
if(NOT EXISTS "${FSIM_CONSUMER_PATH_FILE}")
  message(FATAL_ERROR "installed SCV consumer path was not generated")
endif()
file(READ "${FSIM_CONSUMER_PATH_FILE}" FSIM_CONSUMER_EXECUTABLE)
file(GET_RUNTIME_DEPENDENCIES
  EXECUTABLES "${FSIM_CONSUMER_EXECUTABLE}"
  LIBRARIES "${FSIM_SCV_LIBRARY}"
  DIRECTORIES
    "${FSIM_RELOCATED_STAGE}/${FSIM_BINDIR}"
    "${FSIM_RELOCATED_STAGE}/${FSIM_LIBDIR}"
  RESOLVED_DEPENDENCIES_VAR FSIM_RESOLVED_DEPENDENCIES
  UNRESOLVED_DEPENDENCIES_VAR FSIM_UNRESOLVED_DEPENDENCIES)
set(FSIM_SCV_RUNTIME_PATHS)
set(FSIM_SYSTEMC_RUNTIME_PATHS)
foreach(FSIM_DEPENDENCY IN LISTS FSIM_RESOLVED_DEPENDENCIES)
  get_filename_component(FSIM_DEPENDENCY_NAME "${FSIM_DEPENDENCY}" NAME)
  if(FSIM_DEPENDENCY_NAME MATCHES "(^|lib)scv")
    file(REAL_PATH "${FSIM_DEPENDENCY}" FSIM_DEPENDENCY_REAL)
    list(APPEND FSIM_SCV_RUNTIME_PATHS "${FSIM_DEPENDENCY_REAL}")
  elseif(FSIM_DEPENDENCY_NAME MATCHES "systemc"
      AND NOT FSIM_DEPENDENCY_NAME MATCHES "fsim_systemc")
    file(REAL_PATH "${FSIM_DEPENDENCY}" FSIM_DEPENDENCY_REAL)
    list(APPEND FSIM_SYSTEMC_RUNTIME_PATHS "${FSIM_DEPENDENCY_REAL}")
  endif()
endforeach()
list(REMOVE_DUPLICATES FSIM_SCV_RUNTIME_PATHS)
list(REMOVE_DUPLICATES FSIM_SYSTEMC_RUNTIME_PATHS)
list(LENGTH FSIM_SCV_RUNTIME_PATHS FSIM_SCV_RUNTIME_COUNT)
list(LENGTH FSIM_SYSTEMC_RUNTIME_PATHS FSIM_SYSTEMC_RUNTIME_COUNT)
if(NOT FSIM_SCV_RUNTIME_COUNT EQUAL 1 OR
   NOT FSIM_SYSTEMC_RUNTIME_COUNT EQUAL 1)
  message(FATAL_ERROR
    "installed SCV consumer requires ${FSIM_SCV_RUNTIME_COUNT} SCV and "
    "${FSIM_SYSTEMC_RUNTIME_COUNT} SystemC runtimes")
endif()
file(REAL_PATH "${FSIM_SCV_LIBRARY}" FSIM_EXPECTED_SCV_REAL)
file(REAL_PATH "${FSIM_SYSTEMC_LIBRARY}" FSIM_EXPECTED_SYSTEMC_REAL)
list(GET FSIM_SCV_RUNTIME_PATHS 0 FSIM_RESOLVED_SCV_REAL)
list(GET FSIM_SYSTEMC_RUNTIME_PATHS 0 FSIM_RESOLVED_SYSTEMC_REAL)
if(NOT FSIM_RESOLVED_SCV_REAL STREQUAL FSIM_EXPECTED_SCV_REAL OR
   NOT FSIM_RESOLVED_SYSTEMC_REAL STREQUAL FSIM_EXPECTED_SYSTEMC_REAL)
  message(FATAL_ERROR
    "installed consumer resolved a non-relocated SCV or SystemC runtime")
endif()

get_filename_component(FSIM_CONSUMER_NAME "${FSIM_CONSUMER_EXECUTABLE}" NAME)
file(COPY "${FSIM_CONSUMER_EXECUTABLE}"
  DESTINATION "${FSIM_RELOCATED_STAGE}/${FSIM_BINDIR}")
execute_process(
  COMMAND "${FSIM_RELOCATED_STAGE}/${FSIM_BINDIR}/${FSIM_CONSUMER_NAME}"
  RESULT_VARIABLE FSIM_RUN_RESULT
  OUTPUT_VARIABLE FSIM_RUN_OUTPUT
  ERROR_VARIABLE FSIM_RUN_ERROR)
if(NOT FSIM_RUN_RESULT EQUAL 0)
  message(FATAL_ERROR
    "relocated SCV consumer failed with ${FSIM_RUN_RESULT}\n"
    "${FSIM_RUN_OUTPUT}${FSIM_RUN_ERROR}")
endif()

message(STATUS
  "SCV installed consumer passed: one relocatable shared SCV and SystemC runtime")
