// SPDX-License-Identifier: Apache-2.0
#pragma once

#include "fsim/library/artifact.hpp"

#include <filesystem>
#include <memory>
#include <optional>
#include <span>
#include <string>
#include <string_view>
#include <vector>

namespace fsim::app::workspace {

enum class ArtifactKind { Hdl, SystemCObject, SystemCPlugin };

struct OwnedUnit {
    library::UnitIndexEntry unit;
    std::string source_key;
};

struct UnitDependency {
    std::string library;
    library::UnitIndexEntry unit;
    std::string fingerprint;
};

struct ArtifactRecord {
    std::string id;
    ArtifactKind kind { ArtifactKind::Hdl };
    // Relative to the owning library, generated by allocate_artifact().
    std::filesystem::path path;
    std::vector<std::string> sources;
    std::string fingerprint;
    std::vector<OwnedUnit> units;
    std::vector<UnitDependency> dependencies;
};

struct LibraryLocation {
    std::string name;
    std::filesystem::path directory;
    bool mapped { false };
};

struct LibraryCatalog {
    LibraryLocation location;
    std::vector<ArtifactRecord> artifacts;
};

struct SnapshotRecord {
    std::string name;
    std::filesystem::path path;
};

// Metadata already contains parser-normalized identifiers, including the
// preserved case of VHDL extended identifiers.
[[nodiscard]] std::string unit_identity(const library::UnitIndexEntry&);
[[nodiscard]] bool valid_name(std::string_view);
[[nodiscard]] std::optional<std::string> source_identity(
    const std::filesystem::path&, std::string& error);

class LibraryTransaction;
class SnapshotTransaction;

class Store final {
public:
    // The caller supplies the current directory. No ancestor lookup occurs.
    explicit Store(std::filesystem::path workspace);

    [[nodiscard]] const std::filesystem::path& root() const;
    [[nodiscard]] std::filesystem::path managed_directory() const;
    [[nodiscard]] std::optional<std::vector<LibraryLocation>> library_locations(
        std::string& error) const;
    [[nodiscard]] bool map_library(std::string_view name,
        const std::filesystem::path& directory, std::string& error) const;
    [[nodiscard]] bool unmap_library(
        std::string_view name, std::string& error) const;
    [[nodiscard]] bool delete_artifact(std::string_view library,
        std::string_view artifact_id, std::string& error) const;
    [[nodiscard]] bool delete_library(std::string_view name, std::string& error) const;
    [[nodiscard]] std::optional<LibraryCatalog> read_library(
        std::string_view name, std::string& error) const;
    [[nodiscard]] std::unique_ptr<LibraryTransaction> begin_library(
        std::string_view name, std::string& error) const;
    [[nodiscard]] std::optional<std::filesystem::path> artifact_path(
        const LibraryLocation&, const ArtifactRecord&, std::string& error) const;
    [[nodiscard]] std::unique_ptr<SnapshotTransaction> begin_snapshot(
        std::string_view name, std::string& error) const;
    [[nodiscard]] std::optional<SnapshotRecord> read_snapshot(
        std::string_view name, std::string& error) const;

private:
    std::filesystem::path root_;
};

class LibraryTransaction final {
public:
    ~LibraryTransaction();
    LibraryTransaction(const LibraryTransaction&) = delete;
    LibraryTransaction& operator=(const LibraryTransaction&) = delete;

    [[nodiscard]] const LibraryCatalog& catalog() const;
    [[nodiscard]] std::optional<ArtifactRecord> allocate_artifact(
        ArtifactKind, std::string& error);
    [[nodiscard]] std::filesystem::path artifact_path(
        const ArtifactRecord&) const;
    // Commit removes superseded source ownership, retaining selected units from
    // grouped artifacts. A native object update invalidates linked plugins.
    // Failed compilation or publication leaves the prior catalog untouched.
    [[nodiscard]] bool commit(ArtifactRecord, std::string& error);
    [[nodiscard]] bool commit(std::vector<ArtifactRecord>, std::string& error);
    [[nodiscard]] bool commit(std::vector<ArtifactRecord>,
        std::span<const std::string> replaced_sources, std::string& error);

private:
    struct Impl;
    explicit LibraryTransaction(std::unique_ptr<Impl>);
    std::unique_ptr<Impl> impl_;
    friend class Store;
};

class SnapshotTransaction final {
public:
    ~SnapshotTransaction();
    SnapshotTransaction(const SnapshotTransaction&) = delete;
    SnapshotTransaction& operator=(const SnapshotTransaction&) = delete;

    // This fresh directory does not exist yet, as required by publishers.
    [[nodiscard]] const std::filesystem::path& artifact_path() const;
    [[nodiscard]] bool commit(std::string& error);

private:
    struct Impl;
    explicit SnapshotTransaction(std::unique_ptr<Impl>);
    std::unique_ptr<Impl> impl_;
    friend class Store;
};

} // namespace fsim::app::workspace
