# SPDX-License-Identifier: Apache-2.0

foreach(FSIM_REQUIRED IN ITEMS
    FSIM_SOURCE_DIR
    FSIM_BINARY_DIR
    FSIM_WORK_DIR
    FSIM_BINDIR
    FSIM_LIBDIR
    FSIM_INCLUDEDIR
    FSIM_DOCDIR
    FSIM_EXECUTABLE_NAME
    FSIM_VHDL_EXECUTABLE_NAME
    FSIM_SV_EXECUTABLE_NAME
    FSIM_ELAB_EXECUTABLE_NAME
    FSIM_RUN_EXECUTABLE_NAME
    FSIM_API_LIBRARY_NAME
    FSIM_SYSTEMC_LIBRARY_NAME
    FSIM_API_LIBRARY_DIR)
  if(NOT DEFINED ${FSIM_REQUIRED} OR "${${FSIM_REQUIRED}}" STREQUAL "")
    message(FATAL_ERROR "${FSIM_REQUIRED} is required")
  endif()
endforeach()

file(REMOVE_RECURSE "${FSIM_WORK_DIR}")
set(FSIM_STAGE "${FSIM_WORK_DIR}/staged-é")
file(MAKE_DIRECTORY "${FSIM_WORK_DIR}")
set(FSIM_INSTALL_COMMAND
  "${CMAKE_COMMAND}"
  --install "${FSIM_BINARY_DIR}"
  --prefix "${FSIM_STAGE}"
)
if(DEFINED FSIM_CONFIG AND NOT FSIM_CONFIG STREQUAL "")
  list(APPEND FSIM_INSTALL_COMMAND --config "${FSIM_CONFIG}")
endif()
execute_process(
  COMMAND ${FSIM_INSTALL_COMMAND}
  RESULT_VARIABLE FSIM_INSTALL_RESULT
  OUTPUT_VARIABLE FSIM_INSTALL_OUTPUT
  ERROR_VARIABLE FSIM_INSTALL_ERROR
)
if(NOT FSIM_INSTALL_RESULT EQUAL 0)
  message(FATAL_ERROR
    "staged public install failed with ${FSIM_INSTALL_RESULT}\n"
    "${FSIM_INSTALL_OUTPUT}${FSIM_INSTALL_ERROR}")
endif()

set(FSIM_EXPECTED_PATHS
  "${FSIM_STAGE}/${FSIM_BINDIR}/${FSIM_EXECUTABLE_NAME}"
  "${FSIM_STAGE}/${FSIM_BINDIR}/${FSIM_VHDL_EXECUTABLE_NAME}"
  "${FSIM_STAGE}/${FSIM_BINDIR}/${FSIM_SV_EXECUTABLE_NAME}"
  "${FSIM_STAGE}/${FSIM_BINDIR}/${FSIM_ELAB_EXECUTABLE_NAME}"
  "${FSIM_STAGE}/${FSIM_BINDIR}/${FSIM_RUN_EXECUTABLE_NAME}"
  "${FSIM_STAGE}/${FSIM_API_LIBRARY_DIR}/${FSIM_API_LIBRARY_NAME}"
  "${FSIM_STAGE}/${FSIM_LIBDIR}/${FSIM_SYSTEMC_LIBRARY_NAME}"
  "${FSIM_STAGE}/${FSIM_INCLUDEDIR}/systemc"
  "${FSIM_STAGE}/${FSIM_INCLUDEDIR}/fsim/api.h"
  "${FSIM_STAGE}/${FSIM_INCLUDEDIR}/fsim/systemc.hpp"
  "${FSIM_STAGE}/${FSIM_INCLUDEDIR}/fsim/systemc_abi.h"
  "${FSIM_STAGE}/${FSIM_INCLUDEDIR}/fsim/version.hpp"
  "${FSIM_STAGE}/${FSIM_INCLUDEDIR}/fsim/systemc/datatypes.hpp"
  "${FSIM_STAGE}/${FSIM_DOCDIR}/LICENSE"
  "${FSIM_STAGE}/${FSIM_DOCDIR}/README.md"
  "${FSIM_STAGE}/${FSIM_DOCDIR}/architecture.md"
  "${FSIM_STAGE}/${FSIM_DOCDIR}/systemverilog-uvm.md"
  "${FSIM_STAGE}/${FSIM_DOCDIR}/uvm-tutorial.md"
  "${FSIM_STAGE}/${FSIM_DOCDIR}/uvm-closure-audit.md"
  "${FSIM_STAGE}/${FSIM_DOCDIR}/vhdl-psl.md"
  "${FSIM_STAGE}/${FSIM_DOCDIR}/vhdl-psl-tutorial.md"
  "${FSIM_STAGE}/${FSIM_DOCDIR}/vhdl-psl-closure-audit.md"
  "${FSIM_STAGE}/${FSIM_DOCDIR}/verilog-2005.md"
  "${FSIM_STAGE}/${FSIM_DOCDIR}/verilog-2005-tutorial.md"
  "${FSIM_STAGE}/${FSIM_DOCDIR}/verilog-2005-closure-audit.md"
  "${FSIM_STAGE}/${FSIM_DOCDIR}/v1-release-audit.md"
  "${FSIM_STAGE}/share/fsim/vhdl/ieee-1076-2019/SHA256SUMS"
)
foreach(FSIM_PATH IN LISTS FSIM_EXPECTED_PATHS)
  if(NOT EXISTS "${FSIM_PATH}")
    message(FATAL_ERROR "staged public artifact is missing: ${FSIM_PATH}")
  endif()
endforeach()

foreach(FSIM_HEADER IN ITEMS api.h systemc.hpp systemc_abi.h version.hpp)
  file(SHA256
    "${FSIM_SOURCE_DIR}/include/fsim/${FSIM_HEADER}"
    FSIM_SOURCE_DIGEST)
  file(SHA256
    "${FSIM_STAGE}/${FSIM_INCLUDEDIR}/fsim/${FSIM_HEADER}"
    FSIM_INSTALLED_DIGEST)
  if(NOT FSIM_SOURCE_DIGEST STREQUAL FSIM_INSTALLED_DIGEST)
    message(FATAL_ERROR "installed public header changed: ${FSIM_HEADER}")
  endif()
endforeach()

set(FSIM_INSTALLED_EXECUTABLE
  "${FSIM_STAGE}/${FSIM_BINDIR}/${FSIM_EXECUTABLE_NAME}")
execute_process(
  COMMAND "${FSIM_INSTALLED_EXECUTABLE}" --version
  RESULT_VARIABLE FSIM_VERSION_RESULT
  OUTPUT_VARIABLE FSIM_VERSION_OUTPUT
  ERROR_VARIABLE FSIM_VERSION_ERROR
)
if(NOT FSIM_VERSION_RESULT EQUAL 0
    OR NOT FSIM_VERSION_OUTPUT MATCHES "^fsim 0\\.1\\.0-dev \\(C API 1\\)")
  message(FATAL_ERROR
    "installed version contract failed with ${FSIM_VERSION_RESULT}\n"
    "${FSIM_VERSION_OUTPUT}${FSIM_VERSION_ERROR}")
endif()

execute_process(
  COMMAND
    "${FSIM_STAGE}/${FSIM_BINDIR}/${FSIM_SV_EXECUTABLE_NAME}"
    --help
  RESULT_VARIABLE FSIM_HELP_RESULT
  OUTPUT_VARIABLE FSIM_HELP_OUTPUT
  ERROR_VARIABLE FSIM_HELP_ERROR
)
if(NOT FSIM_HELP_RESULT EQUAL 0
    OR NOT FSIM_HELP_OUTPUT MATCHES "^Usage: fsim-sv")
  message(FATAL_ERROR
    "installed alias help contract failed with ${FSIM_HELP_RESULT}\n"
    "${FSIM_HELP_OUTPUT}${FSIM_HELP_ERROR}")
endif()

execute_process(
  COMMAND
    "${FSIM_STAGE}/${FSIM_BINDIR}/${FSIM_VHDL_EXECUTABLE_NAME}"
    --help
  RESULT_VARIABLE FSIM_VHDL_HELP_RESULT
  OUTPUT_VARIABLE FSIM_VHDL_HELP_OUTPUT
  ERROR_VARIABLE FSIM_VHDL_HELP_ERROR
)
if(NOT FSIM_VHDL_HELP_RESULT EQUAL 0
    OR NOT FSIM_VHDL_HELP_OUTPUT MATCHES "^Usage: fsim-vhdl")
  message(FATAL_ERROR
    "installed VHDL alias help contract failed with ${FSIM_VHDL_HELP_RESULT}\n"
    "${FSIM_VHDL_HELP_OUTPUT}${FSIM_VHDL_HELP_ERROR}")
endif()

execute_process(
  COMMAND "${FSIM_INSTALLED_EXECUTABLE}" --definitely-invalid
  RESULT_VARIABLE FSIM_INVALID_RESULT
  OUTPUT_VARIABLE FSIM_INVALID_OUTPUT
  ERROR_VARIABLE FSIM_INVALID_ERROR
)
if(NOT FSIM_INVALID_RESULT EQUAL 2
    OR NOT FSIM_INVALID_ERROR MATCHES "unknown option")
  message(FATAL_ERROR
    "installed invalid-option contract failed with ${FSIM_INVALID_RESULT}\n"
    "${FSIM_INVALID_OUTPUT}${FSIM_INVALID_ERROR}")
endif()

message(STATUS
  "installed public contract passed in Unicode stage ${FSIM_STAGE}")
