# SPDX-License-Identifier: Apache-2.0

if(NOT DEFINED FSIM_SOURCE_DIR)
  message(FATAL_ERROR "FSIM_SOURCE_DIR is required")
endif()

set(root "${FSIM_SOURCE_DIR}/third_party/ieee-1076-2019")
include("${root}/inventory.cmake")

if(NOT FSIM_IEEE_1076_2019_TAG STREQUAL "1076-2019")
  message(FATAL_ERROR "unexpected IEEE package tag")
endif()
if(NOT FSIM_IEEE_1076_2019_COMMIT MATCHES "^[0-9a-f]+$")
  message(FATAL_ERROR "IEEE package commit is not a lowercase hexadecimal ID")
endif()
string(LENGTH "${FSIM_IEEE_1076_2019_COMMIT}" commit_length)
if(NOT commit_length EQUAL 40)
  message(FATAL_ERROR "IEEE package commit must contain 40 hexadecimal digits")
endif()

set(inventoried_sources)
set(previous_library "")
foreach(entry IN LISTS FSIM_IEEE_1076_2019_SOURCES)
  string(REPLACE "|" ";" fields "${entry}")
  list(LENGTH fields field_count)
  if(NOT field_count EQUAL 3)
    message(FATAL_ERROR "invalid IEEE inventory entry: ${entry}")
  endif()
  list(GET fields 0 library)
  list(GET fields 1 relative_path)
  list(GET fields 2 stage)
  if(NOT library MATCHES "^(std|ieee)$")
    message(FATAL_ERROR "invalid IEEE inventory library: ${entry}")
  endif()
  if(NOT relative_path MATCHES "^${library}/[-_a-z0-9]+\\.vhdl$")
    message(FATAL_ERROR "invalid IEEE inventory path: ${entry}")
  endif()
  if(stage STREQUAL "")
    message(FATAL_ERROR "empty IEEE inventory review stage: ${entry}")
  endif()
  if(NOT EXISTS "${root}/${relative_path}")
    message(FATAL_ERROR "inventoried IEEE source is missing: ${relative_path}")
  endif()
  list(FIND inventoried_sources "${relative_path}" duplicate_index)
  if(NOT duplicate_index EQUAL -1)
    message(FATAL_ERROR "duplicate IEEE inventory source: ${relative_path}")
  endif()
  list(APPEND inventoried_sources "${relative_path}")
endforeach()

file(STRINGS "${root}/SHA256SUMS" checksum_entries)
set(checksummed_sources)
foreach(entry IN LISTS checksum_entries)
  string(LENGTH "${entry}" entry_length)
  if(entry_length LESS 66)
    message(FATAL_ERROR "invalid IEEE checksum entry: ${entry}")
  endif()
  string(SUBSTRING "${entry}" 0 64 expected)
  string(SUBSTRING "${entry}" 64 -1 relative_path)
  string(STRIP "${relative_path}" relative_path)
  if(NOT expected MATCHES "^[0-9a-f][0-9a-f]*$")
    message(FATAL_ERROR "invalid IEEE checksum: ${expected}")
  endif()
  if(NOT relative_path MATCHES "^[A-Za-z0-9_./-][A-Za-z0-9_./-]*$")
    message(FATAL_ERROR "invalid IEEE checksum path: ${relative_path}")
  endif()
  string(LENGTH "${expected}" hash_length)
  if(NOT hash_length EQUAL 64)
    message(FATAL_ERROR "invalid SHA-256 length for ${relative_path}")
  endif()
  if(NOT EXISTS "${root}/${relative_path}")
    message(FATAL_ERROR "checksummed IEEE file is missing: ${relative_path}")
  endif()
  file(SHA256 "${root}/${relative_path}" actual)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "IEEE source checksum mismatch: ${relative_path}")
  endif()
  if(relative_path MATCHES "\\.vhdl$")
    list(APPEND checksummed_sources "${relative_path}")
    file(READ "${root}/${relative_path}" header LIMIT 800)
    if(NOT header MATCHES "Apache License, Version 2.0")
      message(FATAL_ERROR "IEEE source lacks its Apache-2.0 header: ${relative_path}")
    endif()
  endif()
endforeach()

list(SORT inventoried_sources)
list(SORT checksummed_sources)
if(NOT inventoried_sources STREQUAL checksummed_sources)
  message(FATAL_ERROR "IEEE inventory and checksummed VHDL sources differ")
endif()
