# SPDX-License-Identifier: Apache-2.0

cmake_minimum_required(VERSION 3.28)

foreach(FSIM_VARIABLE IN ITEMS FSIM_SOURCE_DIR FSIM_BINARY_DIR FSIM_CTEST_COMMAND)
  if(NOT DEFINED ${FSIM_VARIABLE} OR "${${FSIM_VARIABLE}}" STREQUAL "")
    message(FATAL_ERROR "${FSIM_VARIABLE} is required")
  endif()
endforeach()

include("${CMAKE_CURRENT_LIST_DIR}/CurrentEvidenceOwners.cmake")
fsim_current_registered_ctests(FSIM_REGISTERED_CTESTS)

set(FSIM_LEDGER
  "${FSIM_SOURCE_DIR}/tests/feature_matrix/v3_release_integration_inventory.tsv")
file(STRINGS "${FSIM_LEDGER}" FSIM_ROWS)
list(POP_FRONT FSIM_ROWS FSIM_LICENSE)
list(POP_FRONT FSIM_ROWS FSIM_HEADER)
if(NOT FSIM_LICENSE STREQUAL "# SPDX-License-Identifier: Apache-2.0"
   OR NOT FSIM_HEADER STREQUAL
      "id\tdomain\tinventory\tchecker\texpected_rows\texpected_digest\tstate\towner")
  message(FATAL_ERROR "v3 release integration inventory header changed")
endif()

set(FSIM_OWNER_LEDGER
  "${FSIM_SOURCE_DIR}/tests/feature_matrix/v3_current_obligations.tsv")
file(STRINGS "${FSIM_OWNER_LEDGER}" FSIM_OWNER_ROWS)
foreach(FSIM_OWNER_ROW IN LISTS FSIM_OWNER_ROWS)
  if(FSIM_OWNER_ROW MATCHES "^#" OR FSIM_OWNER_ROW MATCHES "^id\t")
    continue()
  endif()
  string(REPLACE "\t" ";" FSIM_OWNER_FIELDS "${FSIM_OWNER_ROW}")
  list(LENGTH FSIM_OWNER_FIELDS FSIM_OWNER_FIELD_COUNT)
  if(NOT FSIM_OWNER_FIELD_COUNT EQUAL 3)
    message(FATAL_ERROR "current obligation owner row is malformed")
  endif()
  list(GET FSIM_OWNER_FIELDS 0 FSIM_ID)
  if(NOT FSIM_ID MATCHES "^V3INT-[A-Z0-9-]+$")
    continue()
  endif()
  string(SHA256 FSIM_ID_HASH "${FSIM_ID}")
  if(DEFINED FSIM_OWNER_PATH_${FSIM_ID_HASH})
    message(FATAL_ERROR "duplicate current integration owner: ${FSIM_ID}")
  endif()
  list(GET FSIM_OWNER_FIELDS 1 FSIM_PATH)
  list(GET FSIM_OWNER_FIELDS 2 FSIM_OWNER)
  set(FSIM_OWNER_PATH_${FSIM_ID_HASH} "${FSIM_PATH}")
  set(FSIM_OWNER_CTEST_${FSIM_ID_HASH} "${FSIM_OWNER}")
endforeach()

set(FSIM_SEEN_IDS)
set(FSIM_SEEN_DOMAINS)
foreach(FSIM_ROW IN LISTS FSIM_ROWS)
  if(FSIM_ROW MATCHES ";")
    message(FATAL_ERROR "integration row has an invalid list separator")
  endif()
  string(REPLACE "\t" ";" FSIM_FIELDS "${FSIM_ROW}")
  list(LENGTH FSIM_FIELDS FSIM_FIELD_COUNT)
  if(NOT FSIM_FIELD_COUNT EQUAL 8)
    message(FATAL_ERROR "integration row has ${FSIM_FIELD_COUNT} fields")
  endif()
  list(GET FSIM_FIELDS 0 FSIM_ID)
  list(GET FSIM_FIELDS 1 FSIM_DOMAIN)
  list(GET FSIM_FIELDS 2 FSIM_INVENTORY)
  list(GET FSIM_FIELDS 3 FSIM_CHECKER)
  list(GET FSIM_FIELDS 6 FSIM_STATE)
  if(NOT FSIM_ID MATCHES "^V3INT-[A-Z0-9-]+$"
     OR FSIM_DOMAIN STREQUAL "" OR NOT FSIM_STATE STREQUAL "preserved")
    message(FATAL_ERROR "integration row is unresolved: ${FSIM_ID}")
  endif()
  if(FSIM_ID IN_LIST FSIM_SEEN_IDS OR FSIM_DOMAIN IN_LIST FSIM_SEEN_DOMAINS)
    message(FATAL_ERROR "duplicate integration ID or domain: ${FSIM_ID}")
  endif()
  list(APPEND FSIM_SEEN_IDS "${FSIM_ID}")
  list(APPEND FSIM_SEEN_DOMAINS "${FSIM_DOMAIN}")
  fsim_current_evidence_file("${FSIM_INVENTORY}")
  fsim_current_evidence_file("${FSIM_CHECKER}")
  string(SHA256 FSIM_ID_HASH "${FSIM_ID}")
  if(NOT DEFINED FSIM_OWNER_PATH_${FSIM_ID_HASH}
     OR NOT FSIM_INVENTORY STREQUAL FSIM_OWNER_PATH_${FSIM_ID_HASH})
    message(FATAL_ERROR "integration row lacks a current inventory owner: ${FSIM_ID}")
  endif()
  set(FSIM_OWNER "${FSIM_OWNER_CTEST_${FSIM_ID_HASH}}")
  list(FIND FSIM_REGISTERED_CTESTS "${FSIM_OWNER}" FSIM_OWNER_INDEX)
  if(FSIM_OWNER_INDEX EQUAL -1)
    message(FATAL_ERROR "integration owner CTest is missing: ${FSIM_ID}")
  endif()
  file(READ "${FSIM_SOURCE_DIR}/${FSIM_INVENTORY}" FSIM_CHILD_TEXT)
  if(FSIM_CHILD_TEXT MATCHES "\t(active|planned|unresolved|deferred|partial)\t")
    message(FATAL_ERROR "integration child inventory has unresolved rows: ${FSIM_ID}")
  endif()
endforeach()

set(FSIM_REQUIRED_FILE
  "${FSIM_SOURCE_DIR}/tests/feature_matrix/v3_current_required_ids.txt")
file(STRINGS "${FSIM_REQUIRED_FILE}" FSIM_REQUIRED_IDS)
foreach(FSIM_ID IN LISTS FSIM_REQUIRED_IDS)
  if(NOT FSIM_ID MATCHES "^V3INT-[A-Z0-9-]+$")
    continue()
  endif()
  list(FIND FSIM_SEEN_IDS "${FSIM_ID}" FSIM_FOUND)
  if(FSIM_FOUND EQUAL -1)
    message(FATAL_ERROR "required integration ID is missing: ${FSIM_ID}")
  endif()
endforeach()

list(LENGTH FSIM_SEEN_IDS FSIM_DOMAIN_COUNT)
message(STATUS
  "v3 release integration: ${FSIM_DOMAIN_COUNT} resolved domains have registered current owners; additions allow")
