# SPDX-License-Identifier: Apache-2.0
cmake_minimum_required(VERSION 3.25)

if(NOT DEFINED FSIM_SOURCE_DIR)
  message(FATAL_ERROR "FSIM_SOURCE_DIR is required")
endif()

include("${CMAKE_CURRENT_LIST_DIR}/CurrentEvidenceOwners.cmake")

set(inventory "${FSIM_SOURCE_DIR}/packaging/v3-supply-chain-inventory.tsv")
file(STRINGS "${inventory}" rows)
set(ids)
set(paths)
file(STRINGS "${FSIM_SOURCE_DIR}/packaging/source-package-manifest.txt"
  manifest)
foreach(row IN LISTS rows)
  if(row MATCHES "^#" OR row STREQUAL "")
    continue()
  endif()
  string(REPLACE "\t" ";" fields "${row}")
  list(LENGTH fields field_count)
  if(NOT field_count EQUAL 4)
    message(FATAL_ERROR "invalid v3 supply-chain row: ${row}")
  endif()
  list(GET fields 0 id)
  list(GET fields 1 kind)
  list(GET fields 2 path)
  list(GET fields 3 owner)
  if(NOT id MATCHES "^V3SUP-[A-Z0-9-]+$"
      OR id IN_LIST ids OR path IN_LIST paths OR owner STREQUAL ""
      OR NOT kind MATCHES "^(license|notice|sbom|provenance|exclusion|reference-audit)$")
    message(FATAL_ERROR "invalid v3 supply-chain identity/owner: ${row}")
  endif()
  fsim_current_evidence_file("${path}")
  if(NOT path IN_LIST manifest)
    message(FATAL_ERROR "v3 supply-chain input is not packaged: ${path}")
  endif()
  list(APPEND ids "${id}")
  list(APPEND paths "${path}")
endforeach()

file(STRINGS
  "${FSIM_SOURCE_DIR}/tests/feature_matrix/v3_current_required_ids.txt"
  required_ids)
foreach(id IN LISTS required_ids)
  if(id MATCHES "^V3SUP-[A-Z0-9-]+$" AND NOT id IN_LIST ids)
    message(FATAL_ERROR "required v3 supply-chain input is missing: ${id}")
  endif()
endforeach()

foreach(sbom IN ITEMS
    third_party/systemc-3.0.2/systemc-3.0.2.spdx.json
    third_party/scv-2.0.1/scv-2.0.1.spdx.json
    third_party/sqlite-3.53.4/sqlite-3.53.4.spdx.json)
  set(expected_license "Apache-2.0")
  if(sbom MATCHES "^third_party/sqlite-")
    set(expected_license "blessing")
  endif()
  file(READ "${FSIM_SOURCE_DIR}/${sbom}" contents)
  string(JSON spdx_version ERROR_VARIABLE json_error
    GET "${contents}" spdxVersion)
  if(json_error OR NOT spdx_version STREQUAL "SPDX-2.3")
    message(FATAL_ERROR "SPDX SBOM ${sbom} has invalid version")
  endif()
  string(JSON data_license ERROR_VARIABLE json_error
    GET "${contents}" dataLicense)
  if(json_error OR NOT data_license STREQUAL "CC0-1.0")
    message(FATAL_ERROR "SPDX SBOM ${sbom} has invalid data license")
  endif()
  string(JSON package_count ERROR_VARIABLE json_error
    LENGTH "${contents}" packages)
  if(json_error OR package_count LESS 1)
    message(FATAL_ERROR "SPDX SBOM ${sbom} has no packages")
  endif()
  math(EXPR package_last "${package_count} - 1")
  foreach(package_index RANGE 0 ${package_last})
    string(JSON declared ERROR_VARIABLE json_error
      GET "${contents}" packages ${package_index} licenseDeclared)
    if(json_error OR NOT declared STREQUAL expected_license)
      message(FATAL_ERROR "SPDX SBOM ${sbom} has invalid package license")
    endif()
    foreach(field IN ITEMS checksums externalRefs)
      string(JSON item_count ERROR_VARIABLE json_error
        LENGTH "${contents}" packages ${package_index} ${field})
      if(json_error OR item_count LESS 1)
        message(FATAL_ERROR "SPDX SBOM ${sbom} has no ${field}")
      endif()
    endforeach()
  endforeach()
endforeach()

foreach(id IN ITEMS V3SUP-SQLITE-LICENSE V3SUP-SQLITE-NOTICE
    V3SUP-SQLITE-SBOM V3SUP-SQLITE-PROVENANCE V3SUP-SQLITE-SOURCE)
  if(NOT id IN_LIST ids)
    message(FATAL_ERROR "workspace SQLite supply-chain row is missing: ${id}")
  endif()
endforeach()
include("${FSIM_SOURCE_DIR}/cmake/FsimSqlite.cmake")
set(sqlite_root "${FSIM_SOURCE_DIR}/third_party/sqlite-${FSIM_SQLITE_VERSION}")
set(sqlite_archive "${sqlite_root}/${FSIM_SQLITE_ARCHIVE_NAME}")
fsim_sqlite_validate_archive("${sqlite_archive}")
file(SHA3_256 "${sqlite_archive}" sqlite_sha3)
if(NOT sqlite_sha3 STREQUAL
    "628a44cfe82c66aed1ccbbe85a562d2e33ebe64b3288981ed76285612227934e")
  message(FATAL_ERROR "SQLite source archive differs from the upstream SHA3-256 identity")
endif()
file(STRINGS "${sqlite_root}/SOURCE_MANIFEST.txt" sqlite_manifest)
foreach(record IN ITEMS
    "schema=fsim-sqlite-source-v1" "name=SQLite"
    "version=${FSIM_SQLITE_VERSION}" "release_date=2026-07-24"
    "upstream_url=https://www.sqlite.org/2026/sqlite-amalgamation-3530400.zip"
    "archive=${FSIM_SQLITE_ARCHIVE_NAME}" "archive_size=${FSIM_SQLITE_ARCHIVE_SIZE}"
    "archive_sha256=${FSIM_SQLITE_ARCHIVE_SHA256}"
    "archive_sha3_256=${sqlite_sha3}" "source_root=${FSIM_SQLITE_SOURCE_ROOT}"
    "tree_files=4" "tree_sha256=${FSIM_SQLITE_TREE_SHA256}" "license=blessing")
  if(NOT record IN_LIST sqlite_manifest)
    message(FATAL_ERROR "SQLite provenance omits ${record}")
  endif()
endforeach()
foreach(kind IN ITEMS license notice)
  string(TOUPPER "${kind}" filename)
  file(SHA256 "${sqlite_root}/${filename}" digest)
  if(NOT "${kind}_sha256=${digest}" IN_LIST sqlite_manifest)
    message(FATAL_ERROR "SQLite ${kind} differs from its recorded identity")
  endif()
endforeach()
file(READ "${sqlite_root}/sqlite-${FSIM_SQLITE_VERSION}.spdx.json" sqlite_sbom)
foreach(field IN ITEMS versionInfo licenseConcluded licenseDeclared)
  string(JSON value GET "${sqlite_sbom}" packages 0 ${field})
  if(field STREQUAL "versionInfo")
    set(expected "${FSIM_SQLITE_VERSION}")
  else()
    set(expected "blessing")
  endif()
  if(NOT value STREQUAL expected)
    message(FATAL_ERROR "SQLite SBOM has an invalid ${field}")
  endif()
endforeach()
string(JSON sqlite_sbom_sha256 GET "${sqlite_sbom}" packages 0 checksums 0 checksumValue)
string(JSON sqlite_sbom_sha3 GET "${sqlite_sbom}" packages 0 checksums 1 checksumValue)
if(NOT sqlite_sbom_sha256 STREQUAL FSIM_SQLITE_ARCHIVE_SHA256
    OR NOT sqlite_sbom_sha3 STREQUAL sqlite_sha3)
  message(FATAL_ERROR "SQLite SBOM checksums differ from the pinned source")
endif()

set(forbidden_home "/home/" "colin/standards")
list(JOIN forbidden_home "" forbidden_absolute)
set(forbidden_pdf "standards/" ".pdf")
list(JOIN forbidden_pdf "" forbidden_pdf_path)
foreach(path IN LISTS manifest)
  if(path STREQUAL "" OR path MATCHES "^#")
    continue()
  endif()
  string(TOLOWER "${path}" lower_path)
  string(FIND "${lower_path}" "${forbidden_absolute}" absolute_offset)
  string(FIND "${lower_path}" "${forbidden_pdf_path}" pdf_offset)
  if(NOT absolute_offset EQUAL -1 OR NOT pdf_offset EQUAL -1)
    message(FATAL_ERROR "source manifest contains private-reference path material")
  endif()
  if(path MATCHES "[.](cmake|c|cc|cpp|h|hpp|tpp|md|txt|tsv|toml|json|py|sh|sv|svh|v|vhd|vhdl|yml|yaml)$")
    file(READ "${FSIM_SOURCE_DIR}/${path}" contents)
    string(TOLOWER "${contents}" lower_contents)
    string(FIND "${lower_contents}" "${forbidden_absolute}" absolute_offset)
    string(FIND "${lower_contents}" "${forbidden_pdf_path}" pdf_offset)
    if(NOT absolute_offset EQUAL -1 OR NOT pdf_offset EQUAL -1)
      message(FATAL_ERROR "${path} contains private-reference path material")
    endif()
  endif()
endforeach()
