# SPDX-License-Identifier: Apache-2.0

if(NOT DEFINED FSIM_SOURCE_DIR)
  message(FATAL_ERROR "FSIM_SOURCE_DIR is required")
endif()

set(FSIM_DIAGNOSTIC_CATALOG "${FSIM_SOURCE_DIR}/docs/diagnostics.md")
if(NOT EXISTS "${FSIM_DIAGNOSTIC_CATALOG}")
  message(FATAL_ERROR "diagnostic catalog not found: ${FSIM_DIAGNOSTIC_CATALOG}")
endif()

set(
  FSIM_NON_DIAGNOSTIC_MARKERS
  "FSIM-OBJECT-CACHE-V1"
  "FSIM-CACHE-LOCK-V1"
  "FSIM-DESIGN-CACHE-V1"
  "FSIM-DESIGN-CACHE-V3"
)
set(FSIM_CODE_PATTERN "FSIM-[A-Z][A-Z0-9]*(-[A-Z0-9]+)+")

file(
  GLOB_RECURSE
  FSIM_PRODUCTION_SOURCES
  LIST_DIRECTORIES FALSE
  "${FSIM_SOURCE_DIR}/src/*.c"
  "${FSIM_SOURCE_DIR}/src/*.cc"
  "${FSIM_SOURCE_DIR}/src/*.cpp"
  "${FSIM_SOURCE_DIR}/src/*.h"
  "${FSIM_SOURCE_DIR}/src/*.hpp"
  "${FSIM_SOURCE_DIR}/src/*.tpp"
  "${FSIM_SOURCE_DIR}/include/*.h"
  "${FSIM_SOURCE_DIR}/include/*.hpp"
  "${FSIM_SOURCE_DIR}/include/*.tpp"
)

set(FSIM_EMITTED_CODES)
foreach(FSIM_SOURCE IN LISTS FSIM_PRODUCTION_SOURCES)
  file(READ "${FSIM_SOURCE}" FSIM_SOURCE_CONTENTS)
  string(
    REGEX MATCHALL
    "${FSIM_CODE_PATTERN}"
    FSIM_SOURCE_CODES
    "${FSIM_SOURCE_CONTENTS}"
  )
  list(APPEND FSIM_EMITTED_CODES ${FSIM_SOURCE_CODES})
endforeach()
list(REMOVE_ITEM FSIM_EMITTED_CODES ${FSIM_NON_DIAGNOSTIC_MARKERS})
list(REMOVE_DUPLICATES FSIM_EMITTED_CODES)
list(SORT FSIM_EMITTED_CODES)

file(READ "${FSIM_DIAGNOSTIC_CATALOG}" FSIM_CATALOG_CONTENTS)
string(
  REGEX MATCHALL
  "${FSIM_CODE_PATTERN}"
  FSIM_DOCUMENTED_CODES
  "${FSIM_CATALOG_CONTENTS}"
)
list(REMOVE_ITEM FSIM_DOCUMENTED_CODES ${FSIM_NON_DIAGNOSTIC_MARKERS})
set(FSIM_SEEN_DOCUMENTED_CODES)
set(FSIM_DUPLICATE_DOCUMENTED_CODES)
foreach(FSIM_DOCUMENTED_CODE IN LISTS FSIM_DOCUMENTED_CODES)
  list(
    FIND
    FSIM_SEEN_DOCUMENTED_CODES
    "${FSIM_DOCUMENTED_CODE}"
    FSIM_DOCUMENTED_CODE_INDEX
  )
  if(NOT FSIM_DOCUMENTED_CODE_INDEX EQUAL -1)
    list(APPEND FSIM_DUPLICATE_DOCUMENTED_CODES "${FSIM_DOCUMENTED_CODE}")
  else()
    list(APPEND FSIM_SEEN_DOCUMENTED_CODES "${FSIM_DOCUMENTED_CODE}")
  endif()
endforeach()
list(REMOVE_DUPLICATES FSIM_DUPLICATE_DOCUMENTED_CODES)
if(FSIM_DUPLICATE_DOCUMENTED_CODES)
  string(
    JOIN
    ", "
    FSIM_DUPLICATE_DOCUMENTED_TEXT
    ${FSIM_DUPLICATE_DOCUMENTED_CODES}
  )
  message(
    FATAL_ERROR
    "diagnostic catalog contains duplicate codes: "
    "${FSIM_DUPLICATE_DOCUMENTED_TEXT}"
  )
endif()
list(REMOVE_DUPLICATES FSIM_DOCUMENTED_CODES)
list(SORT FSIM_DOCUMENTED_CODES)

set(FSIM_UNDOCUMENTED_CODES ${FSIM_EMITTED_CODES})
list(REMOVE_ITEM FSIM_UNDOCUMENTED_CODES ${FSIM_DOCUMENTED_CODES})
set(FSIM_STALE_CODES ${FSIM_DOCUMENTED_CODES})
list(REMOVE_ITEM FSIM_STALE_CODES ${FSIM_EMITTED_CODES})

if(FSIM_UNDOCUMENTED_CODES OR FSIM_STALE_CODES)
  string(JOIN ", " FSIM_UNDOCUMENTED_TEXT ${FSIM_UNDOCUMENTED_CODES})
  string(JOIN ", " FSIM_STALE_TEXT ${FSIM_STALE_CODES})
  message(
    FATAL_ERROR
    "diagnostic catalog differs from production source\n"
    "  undocumented source codes: ${FSIM_UNDOCUMENTED_TEXT}\n"
    "  documented but unemitted codes: ${FSIM_STALE_TEXT}"
  )
endif()

list(LENGTH FSIM_EMITTED_CODES FSIM_DIAGNOSTIC_CODE_COUNT)
message(
  STATUS
  "diagnostic catalog covers ${FSIM_DIAGNOSTIC_CODE_COUNT} production codes"
)
