# SPDX-License-Identifier: Apache-2.0
cmake_minimum_required(VERSION 3.25)

if(NOT DEFINED FSIM_SOURCE_DIR)
  message(FATAL_ERROR "FSIM_SOURCE_DIR is required")
endif()

set(layout "${FSIM_SOURCE_DIR}/packaging/v3-archive-layout.tsv")
file(STRINGS "${layout}" rows)
set(artifacts)
set(source_artifacts)
set(binary_artifacts)
foreach(row IN LISTS rows)
  if(row MATCHES "^#" OR row STREQUAL "")
    continue()
  endif()
  string(REPLACE "\t" ";" fields "${row}")
  list(LENGTH fields field_count)
  if(NOT field_count EQUAL 6)
    message(FATAL_ERROR "invalid v3 archive-layout row: ${row}")
  endif()
  list(GET fields 0 artifact)
  list(GET fields 1 kind)
  list(GET fields 2 platform)
  list(GET fields 3 compiler)
  list(GET fields 4 llvm)
  list(GET fields 5 owner)
  if(artifact IN_LIST artifacts OR owner STREQUAL ""
      OR NOT artifact MATCHES "^fsim-v[0-9]+[.][0-9]+[.][0-9]+-[A-Za-z0-9_.+-]+[.]zip$")
    message(FATAL_ERROR "invalid v3 archive identity/owner: ${row}")
  endif()
  if(kind STREQUAL "source")
    if(NOT platform STREQUAL "portable" OR NOT compiler STREQUAL "none"
        OR NOT llvm STREQUAL "none")
      message(FATAL_ERROR "invalid v3 source archive row: ${row}")
    endif()
    list(APPEND source_artifacts "${artifact}")
  elseif(kind STREQUAL "binary")
    if(NOT platform MATCHES "^(linux|windows)-x86_64$"
        OR NOT compiler MATCHES "^(clang-22|llvm-mingw-20260616)$"
        OR NOT llvm MATCHES "^(off|22[.]1[.]8)$")
      message(FATAL_ERROR "invalid v3 binary archive row: ${row}")
    endif()
    list(APPEND binary_artifacts "${artifact}")
  else()
    message(FATAL_ERROR "unknown v3 archive kind: ${kind}")
  endif()
  list(APPEND artifacts "${artifact}")
endforeach()

file(STRINGS "${FSIM_SOURCE_DIR}/packaging/v3-release-record.txt" record_rows)
foreach(row IN LISTS record_rows)
  if(row MATCHES "^([a-z0-9_]+)=(.+)$")
    set("record_${CMAKE_MATCH_1}" "${CMAKE_MATCH_2}")
  endif()
endforeach()
foreach(key IN ITEMS source_artifact linux_clang22_no_llvm_artifact
    linux_clang22_llvm22_artifact windows_llvm_mingw_no_llvm_artifact
    windows_llvm_mingw_llvm22_artifact)
  if(NOT DEFINED record_${key} OR "${record_${key}}" STREQUAL "")
    message(FATAL_ERROR "v3 release record omits required archive: ${key}")
  endif()
  set(required "${record_${key}}")
  if(key STREQUAL "source_artifact")
    set(required_kind source_artifacts)
  else()
    set(required_kind binary_artifacts)
  endif()
  if(NOT required IN_LIST ${required_kind})
    message(FATAL_ERROR "missing v3 archive layout entry: ${required}")
  endif()
endforeach()
