# SPDX-License-Identifier: Apache-2.0
cmake_minimum_required(VERSION 3.25)

foreach(required IN ITEMS FSIM_SOURCE_DIR FSIM_BINARY_DIR FSIM_EXECUTABLE)
  if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
    message(FATAL_ERROR "${required} is required")
  endif()
endforeach()

set(inventory "${FSIM_SOURCE_DIR}/tests/feature_matrix/v3_version_identity.tsv")
file(STRINGS "${inventory}" rows)
set(ids)
set(count 0)
foreach(row IN LISTS rows)
  if(row MATCHES "^#" OR row STREQUAL "")
    continue()
  endif()
  string(REPLACE "\t" ";" fields "${row}")
  list(LENGTH fields field_count)
  if(NOT field_count EQUAL 5)
    message(FATAL_ERROR "invalid v3 version-identity row: ${row}")
  endif()
  list(GET fields 0 id)
  list(GET fields 2 path)
  list(GET fields 4 owner)
  if(id IN_LIST ids OR NOT owner STREQUAL "B188-C19"
      OR NOT EXISTS "${FSIM_SOURCE_DIR}/${path}")
    message(FATAL_ERROR "invalid v3 version identity/owner: ${row}")
  endif()
  list(APPEND ids "${id}")
  math(EXPR count "${count} + 1")
endforeach()
if(NOT count EQUAL 11)
  message(FATAL_ERROR "expected 11 v3 version identities, found ${count}")
endif()

function(require_token path token)
  file(READ "${FSIM_SOURCE_DIR}/${path}" contents)
  string(FIND "${contents}" "${token}" offset)
  if(offset EQUAL -1)
    message(FATAL_ERROR "${path} misses v3 identity token: ${token}")
  endif()
endfunction()
require_token(CMakeLists.txt "VERSION 3.0.0")
require_token(include/fsim/version.hpp "version = \"3.0.0\"")
require_token(cmake/fsim.pc.in "Version: @PROJECT_VERSION@")
require_token(packaging/package-policy.txt "release_identity=fsim-v3.0.0")
require_token(packaging/package-policy.txt
  "binary_artifacts=fsim-v3.0.0-linux-x86_64-clang22-no-llvm.zip,fsim-v3.0.0-linux-x86_64-clang22-llvm22.zip,fsim-v3.0.0-windows-x86_64-llvm-mingw-no-llvm.zip,fsim-v3.0.0-windows-x86_64-llvm-mingw-llvm22.zip")
require_token(packaging/v3-release-record.txt "tag_message=fsim v3.0.0")
require_token(.github/workflows/ci.yml
  "binary_archive: fsim-v3.0.0-windows-x86_64-llvm-mingw-no-llvm.zip")
require_token(.github/workflows/ci.yml
  "binary_archive: fsim-v3.0.0-windows-x86_64-llvm-mingw-llvm22.zip")
foreach(target IN ITEMS
    packaging/targets/linux-clang22-no-llvm.txt
    packaging/targets/linux-clang22-llvm22.txt
    packaging/targets/windows-llvm-mingw-no-llvm.txt
    packaging/targets/windows-llvm-mingw-llvm22.txt)
  require_token(${target} "hosted_workers=2")
  require_token(${target} "batch188_required=")
endforeach()

file(READ "${FSIM_BINARY_DIR}/fsim.pc" pc)
string(FIND "${pc}" "Version: 3.0.0" pc_offset)
if(pc_offset EQUAL -1)
  message(FATAL_ERROR "generated fsim.pc is not version 3.0.0")
endif()
execute_process(COMMAND "${FSIM_EXECUTABLE}" --version
  RESULT_VARIABLE version_result OUTPUT_VARIABLE version ERROR_VARIABLE version_error)
string(STRIP "${version}" version)
if(NOT version_result EQUAL 0 OR NOT version STREQUAL "fsim 3.0.0 (C API 1)")
  message(FATAL_ERROR "compiled v3 version identity failed: ${version}${version_error}")
endif()

foreach(path IN ITEMS packaging/package-policy.txt .github/workflows/ci.yml)
  file(READ "${FSIM_SOURCE_DIR}/${path}" contents)
  if(contents MATCHES "fsim-v2[.]0[.]0" OR contents MATCHES "linux-x86_64-gcc13")
    message(FATAL_ERROR "active v3 product/package surface retains v2/GCC identity: ${path}")
  endif()
endforeach()
file(SHA256 "${inventory}" digest)
if(NOT digest STREQUAL "394256500832e38e3e15bbc4715e4494312192de1a39a1eea9bf4e77b3b3be2c")
  message(FATAL_ERROR "v3 version-identity inventory digest changed: ${digest}")
endif()
