# SPDX-License-Identifier: Apache-2.0

cmake_minimum_required(VERSION 3.28)

foreach(FSIM_VARIABLE IN ITEMS FSIM_SOURCE_DIR FSIM_BINARY_DIR
    FSIM_CTEST_COMMAND FSIM_INVENTORY_KIND)
  if(NOT DEFINED ${FSIM_VARIABLE} OR "${${FSIM_VARIABLE}}" STREQUAL "")
    message(FATAL_ERROR "${FSIM_VARIABLE} is required")
  endif()
endforeach()

if(FSIM_INVENTORY_KIND STREQUAL "fst")
  set(FSIM_INVENTORY_FILE
    "${FSIM_SOURCE_DIR}/tests/feature_matrix/fst_inventory.tsv")
  set(FSIM_ID_PATTERN "^FST-C[0-9][0-9]$")
  set(FSIM_HEADER_PREFIX "id\tformats\thdl_profiles")
  set(FSIM_MIDDLE_EVIDENCE "equivalence_evidence")
elseif(FSIM_INVENTORY_KIND STREQUAL "sdf-application")
  set(FSIM_INVENTORY_FILE
    "${FSIM_SOURCE_DIR}/tests/feature_matrix/sdf_application_inventory.tsv")
  set(FSIM_ID_PATTERN "^SDFAPP-C[0-9][0-9]$")
  set(FSIM_HEADER_PREFIX "id\tsdf_revisions\thdl_profiles")
  set(FSIM_MIDDLE_EVIDENCE "engine_evidence")
elseif(FSIM_INVENTORY_KIND STREQUAL "sdf-vital")
  set(FSIM_INVENTORY_FILE
    "${FSIM_SOURCE_DIR}/tests/feature_matrix/sdf_vital_inventory.tsv")
  set(FSIM_ID_PATTERN "^VITALSDF-C[0-9][0-9]$")
  set(FSIM_HEADER_PREFIX "id\tsdf_revisions\thdl_profiles")
  set(FSIM_MIDDLE_EVIDENCE "engine_evidence")
else()
  message(FATAL_ERROR "unknown trace/timing inventory: ${FSIM_INVENTORY_KIND}")
endif()

include("${CMAKE_CURRENT_LIST_DIR}/CurrentEvidenceOwners.cmake")
fsim_current_registered_ctests(FSIM_REGISTERED_CTESTS)

set(FSIM_REQUIRED_FILE
  "${FSIM_SOURCE_DIR}/tests/feature_matrix/v3_current_required_ids.txt")
file(STRINGS "${FSIM_REQUIRED_FILE}" FSIM_ALL_REQUIRED_IDS)
set(FSIM_REQUIRED_IDS)
foreach(FSIM_ID IN LISTS FSIM_ALL_REQUIRED_IDS)
  if(FSIM_ID MATCHES "${FSIM_ID_PATTERN}")
    list(APPEND FSIM_REQUIRED_IDS "${FSIM_ID}")
  endif()
endforeach()
if(NOT FSIM_REQUIRED_IDS)
  message(FATAL_ERROR "${FSIM_INVENTORY_KIND} has no required IDs")
endif()

set(FSIM_SCOPE_FILE
  "${FSIM_SOURCE_DIR}/tests/feature_matrix/current_trace_timing_required.tsv")
file(STRINGS "${FSIM_SCOPE_FILE}" FSIM_SCOPE_ROWS)
list(POP_FRONT FSIM_SCOPE_ROWS FSIM_SCOPE_SPDX)
list(POP_FRONT FSIM_SCOPE_ROWS FSIM_SCOPE_HEADER)
if(NOT FSIM_SCOPE_SPDX STREQUAL "# SPDX-License-Identifier: Apache-2.0"
   OR NOT FSIM_SCOPE_HEADER STREQUAL
      "id\tformats_or_revisions\thdl_profiles\tdomain")
  message(FATAL_ERROR "trace/timing required-scope ledger header changed")
endif()
foreach(FSIM_SCOPE_ROW IN LISTS FSIM_SCOPE_ROWS)
  if(FSIM_SCOPE_ROW MATCHES ";")
    message(FATAL_ERROR "trace/timing scope row has an invalid list separator")
  endif()
  string(REPLACE "\t" ";" FSIM_SCOPE_FIELDS "${FSIM_SCOPE_ROW}")
  list(LENGTH FSIM_SCOPE_FIELDS FSIM_SCOPE_FIELD_COUNT)
  if(NOT FSIM_SCOPE_FIELD_COUNT EQUAL 4)
    message(FATAL_ERROR "trace/timing scope row is malformed")
  endif()
  list(GET FSIM_SCOPE_FIELDS 0 FSIM_SCOPE_ID)
  if(NOT FSIM_SCOPE_ID MATCHES "${FSIM_ID_PATTERN}")
    continue()
  endif()
  string(SHA256 FSIM_SCOPE_HASH "${FSIM_SCOPE_ID}")
  if(DEFINED FSIM_SCOPE_${FSIM_SCOPE_HASH})
    message(FATAL_ERROR "duplicate trace/timing scope ID: ${FSIM_SCOPE_ID}")
  endif()
  set(FSIM_SCOPE_${FSIM_SCOPE_HASH} "${FSIM_SCOPE_FIELDS}")
endforeach()

set(FSIM_LEDGER_FILE
  "${FSIM_SOURCE_DIR}/tests/feature_matrix/v3_current_obligations.tsv")
file(STRINGS "${FSIM_LEDGER_FILE}" FSIM_LEDGER_ROWS)
foreach(FSIM_LEDGER_ROW IN LISTS FSIM_LEDGER_ROWS)
  if(FSIM_LEDGER_ROW MATCHES "^#" OR FSIM_LEDGER_ROW MATCHES "^id\t")
    continue()
  endif()
  if(FSIM_LEDGER_ROW MATCHES ";")
    message(FATAL_ERROR "current obligation ledger has an invalid list separator")
  endif()
  string(REPLACE "\t" ";" FSIM_LEDGER_FIELDS "${FSIM_LEDGER_ROW}")
  list(LENGTH FSIM_LEDGER_FIELDS FSIM_LEDGER_FIELD_COUNT)
  if(NOT FSIM_LEDGER_FIELD_COUNT EQUAL 3)
    message(FATAL_ERROR "current obligation ledger row is malformed")
  endif()
  list(GET FSIM_LEDGER_FIELDS 0 FSIM_LEDGER_ID)
  if(NOT FSIM_LEDGER_ID MATCHES "${FSIM_ID_PATTERN}")
    continue()
  endif()
  string(SHA256 FSIM_ID_HASH "${FSIM_LEDGER_ID}")
  if(DEFINED FSIM_LEDGER_PATH_${FSIM_ID_HASH})
    message(FATAL_ERROR "duplicate current obligation ID: ${FSIM_LEDGER_ID}")
  endif()
  list(GET FSIM_LEDGER_FIELDS 1 FSIM_LEDGER_PATH)
  list(GET FSIM_LEDGER_FIELDS 2 FSIM_LEDGER_OWNER)
  set(FSIM_LEDGER_PATH_${FSIM_ID_HASH} "${FSIM_LEDGER_PATH}")
  set(FSIM_LEDGER_OWNER_${FSIM_ID_HASH} "${FSIM_LEDGER_OWNER}")
endforeach()

set(FSIM_EXPECTED_HEADER
  "${FSIM_HEADER_PREFIX}\tdomain\tboundary\tclosure\tobligation\timplementation_owner\tpositive_evidence\tnegative_evidence\t${FSIM_MIDDLE_EVIDENCE}\tphase_evidence\tartifact_evidence\tdiagnostic_owner\tresource_owner")
file(STRINGS "${FSIM_INVENTORY_FILE}" FSIM_ROWS)
list(POP_FRONT FSIM_ROWS FSIM_SPDX)
list(POP_FRONT FSIM_ROWS FSIM_HEADER)
if(NOT FSIM_SPDX STREQUAL "# SPDX-License-Identifier: Apache-2.0"
   OR NOT FSIM_HEADER STREQUAL FSIM_EXPECTED_HEADER)
  message(FATAL_ERROR "${FSIM_INVENTORY_KIND} inventory header changed")
endif()

set(FSIM_SEEN_IDS)
foreach(FSIM_ROW IN LISTS FSIM_ROWS)
  if(FSIM_ROW MATCHES ";")
    message(FATAL_ERROR "${FSIM_INVENTORY_KIND} row has an invalid list separator")
  endif()
  string(REPLACE "\t" ";" FSIM_FIELDS "${FSIM_ROW}")
  list(LENGTH FSIM_FIELDS FSIM_FIELD_COUNT)
  if(NOT FSIM_FIELD_COUNT EQUAL 15)
    message(FATAL_ERROR "${FSIM_INVENTORY_KIND} row has ${FSIM_FIELD_COUNT} fields")
  endif()
  list(GET FSIM_FIELDS 0 FSIM_ID)
  list(GET FSIM_FIELDS 1 FSIM_FORMATS)
  list(GET FSIM_FIELDS 2 FSIM_PROFILES)
  list(GET FSIM_FIELDS 3 FSIM_DOMAIN)
  list(GET FSIM_FIELDS 4 FSIM_BOUNDARY)
  list(GET FSIM_FIELDS 5 FSIM_CLOSURE)
  list(GET FSIM_FIELDS 6 FSIM_OBLIGATION)
  list(GET FSIM_FIELDS 8 FSIM_POSITIVE_PATH)
  if(NOT FSIM_ID MATCHES "${FSIM_ID_PATTERN}"
     OR FSIM_FORMATS STREQUAL "" OR FSIM_PROFILES STREQUAL ""
     OR FSIM_DOMAIN STREQUAL "" OR FSIM_CLOSURE STREQUAL ""
     OR FSIM_OBLIGATION STREQUAL ""
     OR NOT FSIM_BOUNDARY MATCHES "^(active|preserved)$")
    message(FATAL_ERROR "${FSIM_INVENTORY_KIND} row has invalid scope: ${FSIM_ID}")
  endif()
  list(FIND FSIM_SEEN_IDS "${FSIM_ID}" FSIM_DUPLICATE)
  if(NOT FSIM_DUPLICATE EQUAL -1)
    message(FATAL_ERROR "duplicate ${FSIM_INVENTORY_KIND} ID: ${FSIM_ID}")
  endif()
  list(APPEND FSIM_SEEN_IDS "${FSIM_ID}")
  string(SHA256 FSIM_ID_HASH "${FSIM_ID}")
  set(FSIM_ACTUAL_SCOPE
    "${FSIM_ID};${FSIM_FORMATS};${FSIM_PROFILES};${FSIM_DOMAIN}")
  if(NOT DEFINED FSIM_SCOPE_${FSIM_ID_HASH}
     OR NOT FSIM_ACTUAL_SCOPE STREQUAL FSIM_SCOPE_${FSIM_ID_HASH})
    message(FATAL_ERROR "${FSIM_ID} has no matching required scope")
  endif()
  if(NOT DEFINED FSIM_LEDGER_PATH_${FSIM_ID_HASH}
     OR NOT FSIM_POSITIVE_PATH STREQUAL FSIM_LEDGER_PATH_${FSIM_ID_HASH})
    message(FATAL_ERROR "${FSIM_ID} lacks its current positive-evidence mapping")
  endif()
  set(FSIM_OWNER "${FSIM_LEDGER_OWNER_${FSIM_ID_HASH}}")
  list(FIND FSIM_REGISTERED_CTESTS "${FSIM_OWNER}" FSIM_OWNER_INDEX)
  if(FSIM_OWNER_INDEX EQUAL -1)
    message(FATAL_ERROR "${FSIM_ID} has no registered behavioral owner")
  endif()
  foreach(FSIM_PATH_INDEX RANGE 7 14)
    list(GET FSIM_FIELDS ${FSIM_PATH_INDEX} FSIM_PATH)
    fsim_current_evidence_file("${FSIM_PATH}")
  endforeach()
endforeach()

foreach(FSIM_REQUIRED_ID IN LISTS FSIM_REQUIRED_IDS)
  list(FIND FSIM_SEEN_IDS "${FSIM_REQUIRED_ID}" FSIM_FOUND)
  if(FSIM_FOUND EQUAL -1)
    message(FATAL_ERROR "required ${FSIM_INVENTORY_KIND} ID is missing: ${FSIM_REQUIRED_ID}")
  endif()
endforeach()
list(LENGTH FSIM_SEEN_IDS FSIM_ROW_COUNT)
message(STATUS
  "${FSIM_INVENTORY_KIND} current inventory: ${FSIM_ROW_COUNT} mapped IDs with registered behavioral owners; additions allow")
