# SPDX-License-Identifier: Apache-2.0

cmake_minimum_required(VERSION 3.28)

if(NOT DEFINED FSIM_SOURCE_DIR OR NOT IS_DIRECTORY "${FSIM_SOURCE_DIR}")
  message(FATAL_ERROR "FSIM_SOURCE_DIR must name the source tree")
endif()

set(FSIM_REQUIRED_FILE
  "${FSIM_SOURCE_DIR}/tests/feature_matrix/v1_release_required_ids.txt")
set(FSIM_MATRIX_FILE "${FSIM_SOURCE_DIR}/docs/feature-matrix.md")
if(NOT EXISTS "${FSIM_REQUIRED_FILE}" OR NOT EXISTS "${FSIM_MATRIX_FILE}")
  message(FATAL_ERROR "release case ID inputs are missing")
endif()

file(STRINGS "${FSIM_REQUIRED_FILE}" FSIM_REQUIRED_IDS)
list(FILTER FSIM_REQUIRED_IDS EXCLUDE REGEX
  "^# SPDX-License-Identifier: Apache-2.0$")
if(NOT FSIM_REQUIRED_IDS)
  message(FATAL_ERROR "required release case ID set is empty")
endif()
set(FSIM_UNIQUE_REQUIRED_IDS)
foreach(FSIM_ID IN LISTS FSIM_REQUIRED_IDS)
  if(NOT FSIM_ID MATCHES "^(ML-[0-9][0-9][0-9]|V1-(SV|VH)-[0-9][0-9])$")
    message(FATAL_ERROR "invalid required release case ID: ${FSIM_ID}")
  endif()
  list(FIND FSIM_UNIQUE_REQUIRED_IDS "${FSIM_ID}" FSIM_DUPLICATE)
  if(NOT FSIM_DUPLICATE EQUAL -1)
    message(FATAL_ERROR "duplicate required release case ID: ${FSIM_ID}")
  endif()
  list(APPEND FSIM_UNIQUE_REQUIRED_IDS "${FSIM_ID}")
endforeach()

file(STRINGS "${FSIM_MATRIX_FILE}" FSIM_MATRIX_LINES)
set(FSIM_SEEN_IDS)
foreach(FSIM_ROW IN LISTS FSIM_MATRIX_LINES)
  if(NOT FSIM_ROW MATCHES "^\\| (ML-[0-9][0-9][0-9]|V1-(SV|VH)-[0-9][0-9]) \\|")
    continue()
  endif()
  set(FSIM_ID "${CMAKE_MATCH_1}")
  list(FIND FSIM_SEEN_IDS "${FSIM_ID}" FSIM_DUPLICATE)
  if(NOT FSIM_DUPLICATE EQUAL -1)
    message(FATAL_ERROR "duplicate release case row: ${FSIM_ID}")
  endif()
  list(APPEND FSIM_SEEN_IDS "${FSIM_ID}")
  list(FIND FSIM_REQUIRED_IDS "${FSIM_ID}" FSIM_REQUIRED_INDEX)
  if(NOT FSIM_REQUIRED_INDEX EQUAL -1)
    if(NOT FSIM_ROW MATCHES "\\| execute \\|")
      message(FATAL_ERROR "release case is not executable: ${FSIM_ID}")
    endif()
    if(FSIM_ROW MATCHES "\\| — \\|")
      message(FATAL_ERROR "release case lacks evidence: ${FSIM_ID}")
    endif()
  endif()
endforeach()

foreach(FSIM_ID IN LISTS FSIM_REQUIRED_IDS)
  list(FIND FSIM_SEEN_IDS "${FSIM_ID}" FSIM_FOUND)
  if(FSIM_FOUND EQUAL -1)
    message(FATAL_ERROR "required release case is missing: ${FSIM_ID}")
  endif()
endforeach()

list(LENGTH FSIM_SEEN_IDS FSIM_ROW_COUNT)
message(STATUS
  "release case IDs: ${FSIM_ROW_COUNT} rows contain all required executable IDs; additions allow")
