# SPDX-License-Identifier: Apache-2.0

cmake_policy(SET CMP0007 NEW)
cmake_policy(SET CMP0057 NEW)

if(NOT DEFINED FSIM_SOURCE_DIR)
  message(FATAL_ERROR "FSIM_SOURCE_DIR is required")
endif()

include("${FSIM_SOURCE_DIR}/cmake/FsimSourcePackage.cmake")

function(fsim_validate_source_package_manifest manifest_files actual_files
         output_code output_detail)
  set(FSIM_SEEN)
  set(FSIM_PREVIOUS)
  foreach(FSIM_ENTRY IN LISTS manifest_files)
    if(FSIM_ENTRY STREQUAL ""
       OR FSIM_ENTRY MATCHES "^/"
       OR FSIM_ENTRY MATCHES "^[A-Za-z]:"
       OR FSIM_ENTRY MATCHES "\\\\"
       OR FSIM_ENTRY MATCHES "(^|/)\\.\\.?(/|$)"
       OR FSIM_ENTRY MATCHES "//"
       OR NOT FSIM_ENTRY MATCHES "^[A-Za-z0-9_.+@/-]+$")
      set(${output_code} "PATH" PARENT_SCOPE)
      set(${output_detail} "${FSIM_ENTRY}" PARENT_SCOPE)
      return()
    endif()
    list(FIND FSIM_SEEN "${FSIM_ENTRY}" FSIM_SEEN_INDEX)
    if(NOT FSIM_SEEN_INDEX EQUAL -1)
      set(${output_code} "DUPLICATE" PARENT_SCOPE)
      set(${output_detail} "${FSIM_ENTRY}" PARENT_SCOPE)
      return()
    endif()
    if(NOT "${FSIM_PREVIOUS}" STREQUAL ""
       AND "${FSIM_PREVIOUS}" STRGREATER "${FSIM_ENTRY}")
      set(${output_code} "ORDER" PARENT_SCOPE)
      set(${output_detail} "${FSIM_PREVIOUS}|${FSIM_ENTRY}" PARENT_SCOPE)
      return()
    endif()
    list(APPEND FSIM_SEEN "${FSIM_ENTRY}")
    set(FSIM_PREVIOUS "${FSIM_ENTRY}")
  endforeach()

  foreach(FSIM_ENTRY IN LISTS manifest_files)
    list(FIND actual_files "${FSIM_ENTRY}" FSIM_ACTUAL_INDEX)
    if(FSIM_ACTUAL_INDEX EQUAL -1)
      set(${output_code} "MISSING" PARENT_SCOPE)
      set(${output_detail} "${FSIM_ENTRY}" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  foreach(FSIM_ENTRY IN LISTS actual_files)
    list(FIND manifest_files "${FSIM_ENTRY}" FSIM_MANIFEST_INDEX)
    if(FSIM_MANIFEST_INDEX EQUAL -1)
      set(${output_code} "UNEXPECTED" PARENT_SCOPE)
      set(${output_detail} "${FSIM_ENTRY}" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  set(${output_code} "OK" PARENT_SCOPE)
  set(${output_detail} "" PARENT_SCOPE)
endfunction()

function(fsim_expect_source_manifest_failure expected_code manifest_files
         actual_files)
  fsim_validate_source_package_manifest(
    "${manifest_files}" "${actual_files}" FSIM_CODE FSIM_DETAIL)
  if(NOT FSIM_CODE STREQUAL expected_code)
    message(FATAL_ERROR
      "source-package negative expected ${expected_code}, got ${FSIM_CODE}: "
      "${FSIM_DETAIL}")
  endif()
endfunction()

set(FSIM_MANIFEST
    "${FSIM_SOURCE_DIR}/packaging/source-package-manifest.txt")
if(NOT EXISTS "${FSIM_MANIFEST}")
  message(FATAL_ERROR "source-package manifest is missing: ${FSIM_MANIFEST}")
endif()

fsim_collect_source_package_files("${FSIM_SOURCE_DIR}" FSIM_ACTUAL_FILES)
fsim_load_source_package_exclusions("${FSIM_SOURCE_DIR}")
foreach(FSIM_GENERATED IN ITEMS
    .fsim .fsim/libraries/work/library.sqlite3
    examples/sample/.fsim/snapshots/default/runtime.bin)
  fsim_source_package_is_excluded("${FSIM_GENERATED}" FSIM_EXCLUDED)
  if(NOT FSIM_EXCLUDED)
    message(FATAL_ERROR "source-package policy includes workspace state: ${FSIM_GENERATED}")
  endif()
endforeach()
foreach(FSIM_OWNED IN ITEMS
    docs/workspace-mode.md src/app/application_workspace_store.cpp
    third_party/sqlite-3.53.4/sqlite-amalgamation-3530400.zip)
  fsim_source_package_is_excluded("${FSIM_OWNED}" FSIM_EXCLUDED)
  if(FSIM_EXCLUDED)
    message(FATAL_ERROR "source-package policy excludes workspace source: ${FSIM_OWNED}")
  endif()
endforeach()

if(FSIM_WRITE_SOURCE_PACKAGE_MANIFEST)
  set(FSIM_MANIFEST_CONTENT
      "# SPDX-License-Identifier: Apache-2.0\n# schema=fsim-source-package-manifest-v1\n# Generated by cmake/CheckSourcePackageManifest.cmake.\n")
  foreach(FSIM_ENTRY IN LISTS FSIM_ACTUAL_FILES)
    string(APPEND FSIM_MANIFEST_CONTENT "${FSIM_ENTRY}\n")
  endforeach()
  file(WRITE "${FSIM_MANIFEST}" "${FSIM_MANIFEST_CONTENT}")
endif()

file(STRINGS "${FSIM_MANIFEST}" FSIM_MANIFEST_LINES ENCODING UTF-8)
set(FSIM_MANIFEST_FILES)
foreach(FSIM_LINE IN LISTS FSIM_MANIFEST_LINES)
  if(NOT FSIM_LINE STREQUAL "" AND NOT FSIM_LINE MATCHES "^#")
    list(APPEND FSIM_MANIFEST_FILES "${FSIM_LINE}")
  endif()
endforeach()

fsim_validate_source_package_manifest(
  "${FSIM_MANIFEST_FILES}" "${FSIM_ACTUAL_FILES}" FSIM_CODE FSIM_DETAIL)
if(NOT FSIM_CODE STREQUAL "OK")
  message(FATAL_ERROR
    "source-package manifest validation failed (${FSIM_CODE}): ${FSIM_DETAIL}")
endif()

set(FSIM_BASE a b)
fsim_expect_source_manifest_failure("DUPLICATE" "a;a;b" "${FSIM_BASE}")
fsim_expect_source_manifest_failure("PATH" "../a;b" "${FSIM_BASE}")
fsim_expect_source_manifest_failure("ORDER" "b;a" "${FSIM_BASE}")
fsim_expect_source_manifest_failure("MISSING" "a;b;c" "${FSIM_BASE}")
fsim_expect_source_manifest_failure("UNEXPECTED" "${FSIM_BASE}" "a;b;c")

foreach(FSIM_REQUIRED IN ITEMS
    CMakeLists.txt
    cmake/fsimConfig.cmake.in
    cmake/fsim.pc.in
    cmake/CheckLinuxPackageDefinitions.cmake
    cmake/CheckWindowsPackageDefinitions.cmake
    cmake/RunCleanMachineInstallClosure.cmake
    cmake/RunCompatibilitySmokeClosure.cmake
    cmake/CheckReleaseCandidateLogAudit.cmake
    cmake/CheckV2ReleaseRecords.cmake
    cmake/CheckV2SupplyChain.cmake
    packaging/source-package-exclusions.txt
    packaging/source-package-manifest.txt
    packaging/v2-release-record.txt
    packaging/v2-support-matrix.tsv
    packaging/example-output-freeze.tsv
    packaging/targets/linux-clang22-llvm22.txt
    packaging/targets/linux-gcc13-llvm22.txt
    packaging/targets/linux-gcc13-no-llvm.txt
    packaging/targets/windows-llvm-mingw-llvm22.txt
    packaging/targets/windows-llvm-mingw-no-llvm.txt
    cmake/FsimSqlite.cmake
    docs/workspace-mode.md
    examples/vertical_slice/README.md
    examples/vertical_slice/counter.vhd
    examples/vertical_slice/tb.sv
    examples/vertical_slice/sv_child.sv
    LICENSE
    third_party/ieee-1076-2019/LICENSE
    third_party/systemc-3.0.2/LICENSE
    third_party/systemc-3.0.2/NOTICE
    third_party/systemc-3.0.2/SOURCE_MANIFEST.txt
    third_party/systemc-3.0.2/systemc-3.0.2.spdx.json
    third_party/scv-2.0.1/LICENSE
    third_party/scv-2.0.1/NOTICE
    third_party/scv-2.0.1/PATCHES.txt
    third_party/scv-2.0.1/patches/scv-bag-mutable-random.patch
    third_party/scv-2.0.1/patches/scv-int-range-overflow.patch
    third_party/scv-2.0.1/patches/scv-nested-extension-constructors.patch
    third_party/scv-2.0.1/patches/scv-range-size-overflow.patch
    third_party/scv-2.0.1/patches/scv-stream-core-lifetime.patch
    third_party/scv-2.0.1/scv-2.0.1.spdx.json
    third_party/sqlite-3.53.4/LICENSE
    third_party/sqlite-3.53.4/NOTICE
    third_party/sqlite-3.53.4/README.md
    third_party/sqlite-3.53.4/SOURCE_MANIFEST.txt
    third_party/sqlite-3.53.4/sqlite-3.53.4.spdx.json
    third_party/sqlite-3.53.4/sqlite-amalgamation-3530400.zip)
  list(FIND FSIM_MANIFEST_FILES "${FSIM_REQUIRED}" FSIM_REQUIRED_INDEX)
  if(FSIM_REQUIRED_INDEX EQUAL -1)
    message(FATAL_ERROR
      "source-package manifest omits required owned input: ${FSIM_REQUIRED}")
  endif()
endforeach()

list(LENGTH FSIM_MANIFEST_FILES FSIM_FILE_COUNT)
message(STATUS
  "source-package manifest: ${FSIM_FILE_COUNT} ordered files, 26 exclusions, "
  "five negative classes")
