# SPDX-License-Identifier: Apache-2.0

cmake_policy(SET CMP0007 NEW)
cmake_policy(SET CMP0057 NEW)

if(NOT DEFINED FSIM_SOURCE_DIR)
  message(FATAL_ERROR "FSIM_SOURCE_DIR is required")
endif()

set(FSIM_BASELINES
  "${FSIM_SOURCE_DIR}/tests/feature_matrix/v2_performance_baselines.tsv")
if(NOT EXISTS "${FSIM_BASELINES}")
  message(FATAL_ERROR "v2 performance baseline matrix is missing")
endif()

file(STRINGS "${FSIM_BASELINES}" FSIM_LINES)
list(POP_FRONT FSIM_LINES FSIM_LICENSE)
list(POP_FRONT FSIM_LINES FSIM_HEADER)
if(NOT FSIM_LICENSE STREQUAL "# SPDX-License-Identifier: Apache-2.0")
  message(FATAL_ERROR "v2 performance baseline matrix lost SPDX ownership")
endif()
set(FSIM_EXPECTED_HEADER
  "id\tchange\tplatform\ttoolchain\tconfiguration\tworkload\tmetric\tdirection\tunit\tobserved\tthreshold\tevidence")
if(NOT FSIM_HEADER STREQUAL FSIM_EXPECTED_HEADER)
  message(FATAL_ERROR "v2 performance baseline header drifted")
endif()

list(LENGTH FSIM_LINES FSIM_ROW_COUNT)
if(NOT FSIM_ROW_COUNT EQUAL 44)
  message(FATAL_ERROR
    "v2 Linux performance baseline matrix requires exactly 44 rows")
endif()

set(FSIM_IDS)
set(FSIM_CHANGES)
set(FSIM_TOOLCHAINS)
set(FSIM_MINIMUM_COUNT 0)
foreach(FSIM_LINE IN LISTS FSIM_LINES)
  string(REPLACE "\t" ";" FSIM_FIELDS "${FSIM_LINE}")
  list(LENGTH FSIM_FIELDS FSIM_FIELD_COUNT)
  if(NOT FSIM_FIELD_COUNT EQUAL 12)
    message(FATAL_ERROR "v2 performance baseline row has ${FSIM_FIELD_COUNT} fields")
  endif()
  list(GET FSIM_FIELDS 0 FSIM_ID)
  list(GET FSIM_FIELDS 1 FSIM_CHANGE)
  list(GET FSIM_FIELDS 2 FSIM_PLATFORM)
  list(GET FSIM_FIELDS 3 FSIM_TOOLCHAIN)
  list(GET FSIM_FIELDS 4 FSIM_CONFIGURATION)
  list(GET FSIM_FIELDS 7 FSIM_DIRECTION)
  list(GET FSIM_FIELDS 9 FSIM_OBSERVED)
  list(GET FSIM_FIELDS 10 FSIM_THRESHOLD)
  list(GET FSIM_FIELDS 11 FSIM_EVIDENCE)
  if(FSIM_ID IN_LIST FSIM_IDS)
    message(FATAL_ERROR "duplicate v2 performance baseline id: ${FSIM_ID}")
  endif()
  list(APPEND FSIM_IDS "${FSIM_ID}")
  list(APPEND FSIM_CHANGES "${FSIM_CHANGE}")
  list(APPEND FSIM_TOOLCHAINS "${FSIM_TOOLCHAIN}")
  if(NOT FSIM_PLATFORM STREQUAL "linux" OR
     NOT FSIM_CONFIGURATION STREQUAL "Debug")
    message(FATAL_ERROR "provisional performance baseline must remain Linux Debug")
  endif()
  if(NOT FSIM_TOOLCHAIN MATCHES "^(clang-22|gcc-13)$")
    message(FATAL_ERROR "unsupported Linux baseline toolchain: ${FSIM_TOOLCHAIN}")
  endif()
  if(NOT FSIM_OBSERVED MATCHES "^[0-9]+$" OR
     NOT FSIM_THRESHOLD MATCHES "^[0-9]+$")
    message(FATAL_ERROR "performance observations and thresholds must be integers")
  endif()
  if(FSIM_DIRECTION STREQUAL "maximum")
    if(FSIM_THRESHOLD LESS FSIM_OBSERVED)
      message(FATAL_ERROR "maximum threshold is below observation: ${FSIM_ID}")
    endif()
  elseif(FSIM_DIRECTION STREQUAL "minimum")
    math(EXPR FSIM_MINIMUM_COUNT "${FSIM_MINIMUM_COUNT} + 1")
    if(FSIM_THRESHOLD GREATER FSIM_OBSERVED)
      message(FATAL_ERROR "minimum threshold is above observation: ${FSIM_ID}")
    endif()
  else()
    message(FATAL_ERROR "invalid performance threshold direction: ${FSIM_ID}")
  endif()
  if(NOT FSIM_EVIDENCE MATCHES
      "^build/qualification/batch175-change(09|10|11|12|13|14|15|16)-.*\\.log$")
    message(FATAL_ERROR "performance evidence path escaped Batch 175: ${FSIM_ID}")
  endif()
endforeach()

list(REMOVE_DUPLICATES FSIM_CHANGES)
list(SORT FSIM_CHANGES)
set(FSIM_EXPECTED_CHANGES
  B175-C09 B175-C10 B175-C11 B175-C12 B175-C13 B175-C14 B175-C15 B175-C16)
if(NOT FSIM_CHANGES STREQUAL FSIM_EXPECTED_CHANGES)
  message(FATAL_ERROR "v2 performance baselines must cover Changes 9-16")
endif()
list(REMOVE_DUPLICATES FSIM_TOOLCHAINS)
list(SORT FSIM_TOOLCHAINS)
if(NOT FSIM_TOOLCHAINS STREQUAL "clang-22;gcc-13")
  message(FATAL_ERROR "v2 performance baselines lost a Linux compiler family")
endif()
if(NOT FSIM_MINIMUM_COUNT EQUAL 2)
  message(FATAL_ERROR "v2 performance baselines require two throughput floors")
endif()

file(SHA256 "${FSIM_BASELINES}" FSIM_DIGEST)
set(FSIM_EXPECTED_DIGEST
  "4c9f07b36a3b9dba16f76f983a5478b2ef4e3ca514efa6f032a24b16940792cf")
if(NOT FSIM_DIGEST STREQUAL FSIM_EXPECTED_DIGEST)
  message(FATAL_ERROR
    "v2 performance baseline digest drifted: expected=${FSIM_EXPECTED_DIGEST} actual=${FSIM_DIGEST}")
endif()

message(STATUS
  "v2 Linux performance baselines passed: rows=${FSIM_ROW_COUNT} digest=${FSIM_DIGEST}")
