# SPDX-License-Identifier: Apache-2.0
cmake_minimum_required(VERSION 3.25)

if(NOT DEFINED FSIM_SOURCE_DIR)
  message(FATAL_ERROR "FSIM_SOURCE_DIR is required")
endif()

set(inventory "${FSIM_SOURCE_DIR}/packaging/v3-supply-chain-inventory.tsv")
file(STRINGS "${inventory}" rows)
set(ids)
set(paths)
set(count 0)
foreach(row IN LISTS rows)
  if(row MATCHES "^#" OR row STREQUAL "")
    continue()
  endif()
  string(REPLACE "\t" ";" fields "${row}")
  list(LENGTH fields field_count)
  if(NOT field_count EQUAL 4)
    message(FATAL_ERROR "invalid v3 supply-chain row: ${row}")
  endif()
  list(GET fields 0 id)
  list(GET fields 1 kind)
  list(GET fields 2 path)
  list(GET fields 3 owner)
  if(id IN_LIST ids OR path IN_LIST paths OR NOT owner STREQUAL "B188-C17"
      OR NOT kind MATCHES "^(license|notice|sbom|provenance|exclusion|reference-audit)$")
    message(FATAL_ERROR "invalid v3 supply-chain identity/owner: ${row}")
  endif()
  if(NOT EXISTS "${FSIM_SOURCE_DIR}/${path}")
    message(FATAL_ERROR "missing v3 supply-chain input: ${path}")
  endif()
  list(APPEND ids "${id}")
  list(APPEND paths "${path}")
  math(EXPR count "${count} + 1")
endforeach()
if(NOT count EQUAL 13)
  message(FATAL_ERROR "expected 13 v3 supply-chain rows, found ${count}")
endif()

foreach(sbom IN ITEMS
    third_party/systemc-3.0.2/systemc-3.0.2.spdx.json
    third_party/scv-2.0.1/scv-2.0.1.spdx.json)
  file(READ "${FSIM_SOURCE_DIR}/${sbom}" contents)
  foreach(token IN ITEMS
      "\"spdxVersion\": \"SPDX-2.3\""
      "\"dataLicense\": \"CC0-1.0\""
      "\"licenseDeclared\": \"Apache-2.0\""
      "\"checksums\""
      "\"externalRefs\"")
    if(NOT contents MATCHES "${token}")
      message(FATAL_ERROR "SPDX SBOM ${sbom} misses ${token}")
    endif()
  endforeach()
endforeach()

file(STRINGS
  "${FSIM_SOURCE_DIR}/packaging/source-package-manifest.txt" manifest)
set(forbidden_home "/home/" "colin/standards")
list(JOIN forbidden_home "" forbidden_absolute)
set(forbidden_pdf "standards/" ".pdf")
list(JOIN forbidden_pdf "" forbidden_pdf_path)
foreach(path IN LISTS manifest)
  if(path STREQUAL "" OR path MATCHES "^#")
    continue()
  endif()
  string(TOLOWER "${path}" lower_path)
  string(FIND "${lower_path}" "${forbidden_absolute}" absolute_offset)
  string(FIND "${lower_path}" "${forbidden_pdf_path}" pdf_offset)
  if(NOT absolute_offset EQUAL -1 OR NOT pdf_offset EQUAL -1)
    message(FATAL_ERROR "source manifest contains private-reference path material")
  endif()
  if(path MATCHES "[.](cmake|c|cc|cpp|h|hpp|tpp|md|txt|tsv|toml|json|py|sh|sv|svh|v|vhd|vhdl|yml|yaml)$")
    file(READ "${FSIM_SOURCE_DIR}/${path}" contents)
    string(TOLOWER "${contents}" lower_contents)
    string(FIND "${lower_contents}" "${forbidden_absolute}" absolute_offset)
    string(FIND "${lower_contents}" "${forbidden_pdf_path}" pdf_offset)
    if(NOT absolute_offset EQUAL -1 OR NOT pdf_offset EQUAL -1)
      message(FATAL_ERROR "${path} contains private-reference path material")
    endif()
  endif()
endforeach()

file(SHA256 "${inventory}" digest)
if(NOT digest STREQUAL "991174ef94f597bf5c4b956619e6c102bebe3adfc477e04becd99c1ff673b626")
  message(FATAL_ERROR "v3 supply-chain inventory digest changed: ${digest}")
endif()
