# SPDX-License-Identifier: Apache-2.0

if(NOT DEFINED FSIM_SOURCE_DIR)
  message(FATAL_ERROR "FSIM_SOURCE_DIR is required")
endif()
include("${CMAKE_CURRENT_LIST_DIR}/CurrentEvidenceOwners.cmake")
fsim_current_registered_ctests(FSIM_REGISTERED_CTESTS)

set(FSIM_CORPUS "${FSIM_SOURCE_DIR}/docs/v1-portability-corpus.txt")
if(NOT EXISTS "${FSIM_CORPUS}")
  message(FATAL_ERROR "v1 portability corpus inputs are missing")
endif()
file(STRINGS "${FSIM_CORPUS}" FSIM_LINES)

set(FSIM_IDS "")
set(FSIM_ALL_MODES "")
set(FSIM_ROW_COUNT 0)
foreach(FSIM_LINE IN LISTS FSIM_LINES)
  if(FSIM_LINE MATCHES "^#" OR FSIM_LINE STREQUAL "")
    continue()
  endif()
  string(REPLACE "|" ";" FSIM_FIELDS "${FSIM_LINE}")
  list(LENGTH FSIM_FIELDS FSIM_FIELD_COUNT)
  if(NOT FSIM_FIELD_COUNT EQUAL 6)
    message(FATAL_ERROR "malformed portability row: ${FSIM_LINE}")
  endif()
  list(GET FSIM_FIELDS 0 FSIM_ID)
  list(GET FSIM_FIELDS 1 FSIM_SURFACE)
  list(GET FSIM_FIELDS 2 FSIM_MODES)
  list(GET FSIM_FIELDS 3 FSIM_CTEST)
  list(GET FSIM_FIELDS 4 FSIM_EVIDENCE)
  list(GET FSIM_FIELDS 5 FSIM_MARKER)
  if(NOT FSIM_ID MATCHES "^PORT-[0-9][0-9][0-9]$")
    message(FATAL_ERROR "invalid portability ID: ${FSIM_ID}")
  endif()
  list(FIND FSIM_IDS "${FSIM_ID}" FSIM_DUPLICATE_INDEX)
  if(NOT FSIM_DUPLICATE_INDEX EQUAL -1)
    message(FATAL_ERROR "duplicate portability ID: ${FSIM_ID}")
  endif()
  list(APPEND FSIM_IDS "${FSIM_ID}")
  string(APPEND FSIM_ALL_MODES "+${FSIM_MODES}")
  list(FIND FSIM_REGISTERED_CTESTS "${FSIM_CTEST}" FSIM_CTEST_INDEX)
  if(FSIM_CTEST_INDEX EQUAL -1)
    message(FATAL_ERROR
      "${FSIM_ID} names an unregistered CTest: ${FSIM_CTEST}")
  endif()
  fsim_current_evidence_file("${FSIM_EVIDENCE}")
  set(FSIM_EVIDENCE_PATH "${FSIM_SOURCE_DIR}/${FSIM_EVIDENCE}")
  file(READ "${FSIM_EVIDENCE_PATH}" FSIM_EVIDENCE_CONTENTS)
  string(FIND "${FSIM_EVIDENCE_CONTENTS}" "${FSIM_MARKER}" FSIM_MARKER_INDEX)
  if(FSIM_MARKER_INDEX EQUAL -1)
    message(FATAL_ERROR
      "${FSIM_ID} lost marker '${FSIM_MARKER}' in ${FSIM_EVIDENCE}")
  endif()
  math(EXPR FSIM_ROW_COUNT "${FSIM_ROW_COUNT} + 1")
endforeach()

foreach(FSIM_REQUIRED_MODE IN ITEMS
    Debug Release interpreter LLVM-O0 LLVM-O2 cold warm edit api abi plugin
    callback debugger vcd files path newline resources)
  string(FIND "${FSIM_ALL_MODES}" "${FSIM_REQUIRED_MODE}" FSIM_MODE_INDEX)
  if(FSIM_MODE_INDEX EQUAL -1)
    message(FATAL_ERROR
      "portability corpus lacks required mode: ${FSIM_REQUIRED_MODE}")
  endif()
endforeach()
set(FSIM_REQUIRED_IDS_FILE
  "${FSIM_SOURCE_DIR}/tests/feature_matrix/v1_portability_required_ids.txt")
if(NOT EXISTS "${FSIM_REQUIRED_IDS_FILE}")
  message(FATAL_ERROR "required portability ID set is missing")
endif()
file(STRINGS "${FSIM_REQUIRED_IDS_FILE}" FSIM_REQUIRED_IDS)
list(FILTER FSIM_REQUIRED_IDS EXCLUDE REGEX
  "^# SPDX-License-Identifier: Apache-2.0$")
if(NOT FSIM_REQUIRED_IDS)
  message(FATAL_ERROR "required portability ID set is empty")
endif()
set(FSIM_SEEN_REQUIRED_IDS)
foreach(FSIM_REQUIRED_ID IN LISTS FSIM_REQUIRED_IDS)
  if(NOT FSIM_REQUIRED_ID MATCHES "^PORT-[0-9][0-9][0-9]$")
    message(FATAL_ERROR "invalid required portability ID: ${FSIM_REQUIRED_ID}")
  endif()
  list(FIND FSIM_SEEN_REQUIRED_IDS "${FSIM_REQUIRED_ID}" FSIM_SEEN_INDEX)
  if(NOT FSIM_SEEN_INDEX EQUAL -1)
    message(FATAL_ERROR "duplicate required portability ID: ${FSIM_REQUIRED_ID}")
  endif()
  list(APPEND FSIM_SEEN_REQUIRED_IDS "${FSIM_REQUIRED_ID}")
  list(FIND FSIM_IDS "${FSIM_REQUIRED_ID}" FSIM_REQUIRED_INDEX)
  if(FSIM_REQUIRED_INDEX EQUAL -1)
    message(FATAL_ERROR "portability corpus lacks ${FSIM_REQUIRED_ID}")
  endif()
endforeach()

message(STATUS
  "portability corpus: ${FSIM_ROW_COUNT} rows cover Debug/Release, interpreter, "
  "LLVM O0/O2, cold/warm/edit, API/ABI, plug-in, debugger/VCD, files, "
  "path/newline, callbacks, and bounded resources; additions allowed")
