# SPDX-License-Identifier: Apache-2.0

# Apply fsim's governed patches to a fetched Tcl source tree. MODE=verify only
# checks the patch set against its recorded digests. Each patch applies
# exactly between input and output digest checks; a tree whose files already
# match every output digest is accepted unchanged.

cmake_minimum_required(VERSION 3.25)

set(FSIM_TCL_PATCH_MANIFEST_SHA256
  "7eaf83a2e947be91a6744bc7871abbb71bb1ca8ea58116a226bb2ca08a0391ba")

foreach(required IN ITEMS FSIM_SOURCE_DIR FSIM_TCL_VERSION FSIM_TCL_SOURCE_SHA256)
  if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
    message(FATAL_ERROR "${required} is required")
  endif()
endforeach()
if(NOT DEFINED MODE)
  set(MODE apply)
endif()
if(NOT MODE MATCHES "^(apply|verify)$")
  message(FATAL_ERROR "unsupported Tcl patch mode: ${MODE}")
endif()

set(patch_root "${FSIM_SOURCE_DIR}/third_party/tcl-${FSIM_TCL_VERSION}")
set(manifest "${patch_root}/PATCHES.txt")
if(NOT EXISTS "${manifest}")
  message(FATAL_ERROR "Tcl patch manifest is missing: ${manifest}")
endif()
file(SHA256 "${manifest}" manifest_digest)
if(NOT manifest_digest STREQUAL FSIM_TCL_PATCH_MANIFEST_SHA256)
  message(FATAL_ERROR "Tcl patch manifest SHA-256 mismatch: ${manifest_digest}")
endif()
file(STRINGS "${manifest}" rows)
foreach(token IN ITEMS
    "schema=fsim-tcl-patch-set-v1"
    "upstream_version=${FSIM_TCL_VERSION}"
    "upstream_archive_sha256=${FSIM_TCL_SOURCE_SHA256}")
  if(NOT token IN_LIST rows)
    message(FATAL_ERROR "Tcl patch manifest omits ${token}")
  endif()
endforeach()

set(patches)
set(patched_files)
foreach(row IN LISTS rows)
  if(row MATCHES "^patch=([a-z0-9-]+)[|]([0-9a-f]+)[|]([A-Za-z0-9/._-]+)$")
    set(name "${CMAKE_MATCH_1}")
    set(expected "${CMAKE_MATCH_2}")
    set(patch_file "${patch_root}/${CMAKE_MATCH_3}")
    if(NOT EXISTS "${patch_file}")
      message(FATAL_ERROR "Tcl patch ${name} is missing: ${patch_file}")
    endif()
    file(SHA256 "${patch_file}" digest)
    if(NOT digest STREQUAL expected)
      message(FATAL_ERROR "Tcl patch ${name} SHA-256 mismatch: ${digest}")
    endif()
    list(APPEND patches "${name}")
    set("patch_file_${name}" "${patch_file}")
    set("patch_rows_${name}")
  elseif(row MATCHES "^file=([a-z0-9-]+)[|]([A-Za-z0-9/._-]+)[|]([0-9a-f]+)[|]([0-9a-f]+)$")
    set(name "${CMAKE_MATCH_1}")
    set(path "${CMAKE_MATCH_2}")
    if(NOT name IN_LIST patches)
      message(FATAL_ERROR "Tcl patch file row precedes its patch: ${row}")
    endif()
    if(path IN_LIST patched_files)
      message(FATAL_ERROR "Tcl patches must change disjoint files: ${path}")
    endif()
    list(APPEND patched_files "${path}")
    list(APPEND "patch_rows_${name}"
      "${path}|${CMAKE_MATCH_3}|${CMAKE_MATCH_4}")
  endif()
endforeach()
list(LENGTH patches patch_count)
if(patch_count EQUAL 0 OR NOT "patch_count=${patch_count}" IN_LIST rows)
  message(FATAL_ERROR "Tcl patch manifest count does not match its patches")
endif()
foreach(name IN LISTS patches)
  if(NOT patch_rows_${name})
    message(FATAL_ERROR "Tcl patch ${name} records no changed files")
  endif()
endforeach()

if(MODE STREQUAL "verify")
  message(STATUS
    "Tcl ${FSIM_TCL_VERSION} patch set: ${patch_count} governed patch(es)")
  return()
endif()

foreach(required IN ITEMS SOURCE_DIR PATCH_EXECUTABLE)
  if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
    message(FATAL_ERROR "${required} is required")
  endif()
endforeach()

function(fsim_tcl_patch_state name output_state)
  set(inputs TRUE)
  set(outputs TRUE)
  foreach(record IN LISTS patch_rows_${name})
    string(REPLACE "|" ";" fields "${record}")
    list(GET fields 0 path)
    list(GET fields 1 input)
    list(GET fields 2 output)
    set(digest "")
    if(EXISTS "${SOURCE_DIR}/${path}")
      file(SHA256 "${SOURCE_DIR}/${path}" digest)
    endif()
    if(NOT digest STREQUAL input)
      set(inputs FALSE)
    endif()
    if(NOT digest STREQUAL output)
      set(outputs FALSE)
    endif()
  endforeach()
  if(outputs)
    set(${output_state} applied PARENT_SCOPE)
  elseif(inputs)
    set(${output_state} pristine PARENT_SCOPE)
  else()
    set(${output_state} unexpected PARENT_SCOPE)
  endif()
endfunction()

foreach(name IN LISTS patches)
  fsim_tcl_patch_state("${name}" state)
  if(state STREQUAL "applied")
    message(STATUS "Tcl patch ${name} is already applied")
    continue()
  elseif(state STREQUAL "unexpected")
    message(FATAL_ERROR
      "Tcl source for patch ${name} is neither the governed "
      "${FSIM_TCL_VERSION} release nor its patched result: ${SOURCE_DIR}")
  endif()
  execute_process(
    COMMAND "${PATCH_EXECUTABLE}" -p1 --forward --batch --fuzz=0
      --no-backup-if-mismatch -d "${SOURCE_DIR}" -i "${patch_file_${name}}"
    RESULT_VARIABLE result
    OUTPUT_VARIABLE output
    ERROR_VARIABLE error)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Tcl patch ${name} failed:\n${output}${error}")
  endif()
  fsim_tcl_patch_state("${name}" state)
  if(NOT state STREQUAL "applied")
    message(FATAL_ERROR "Tcl patch ${name} produced unexpected sources")
  endif()
  message(STATUS "applied Tcl patch ${name}")
endforeach()
